#ifndef __CCU_LED_CANADDRES_H__
#define __CCU_LED_CANADDRES_H__


#include "stm32f4xx.h"
/*定义输入GPIO端口*/
#define  CCULED_CANADD0_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD0_GPIO 			 GPIOF
#define  CCULED_CANADD0_GPIO_PIN 	 GPIO_Pin_6
#define  CCULED_CANADD0_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD0_GPIO,CCULED_CANADD0_GPIO_PIN)

#define  CCULED_CANADD1_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD1_GPIO 			 GPIOF
#define  CCULED_CANADD1_GPIO_PIN 	 GPIO_Pin_7
#define  CCULED_CANADD1_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD1_GPIO,CCULED_CANADD1_GPIO_PIN)

#define  CCULED_CANADD2_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD2_GPIO 			 GPIOF
#define  CCULED_CANADD2_GPIO_PIN 	 GPIO_Pin_8
#define  CCULED_CANADD2_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD2_GPIO,CCULED_CANADD2_GPIO_PIN)

#define  CCULED_CANADD3_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD3_GPIO 			 GPIOF
#define  CCULED_CANADD3_GPIO_PIN 	 GPIO_Pin_9
#define  CCULED_CANADD3_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD3_GPIO,CCULED_CANADD3_GPIO_PIN)

#define  CCULED_CANADD4_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD4_GPIO 			 GPIOF
#define  CCULED_CANADD4_GPIO_PIN 	 GPIO_Pin_15
#define  CCULED_CANADD4_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD4_GPIO,CCULED_CANADD4_GPIO_PIN)

#define  CCULED_CANADD5_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD5_GPIO 			 GPIOF
#define  CCULED_CANADD5_GPIO_PIN 	 GPIO_Pin_14
#define  CCULED_CANADD5_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD5_GPIO,CCULED_CANADD5_GPIO_PIN)

#define  CCULED_CANADD6_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD6_GPIO 			 GPIOF
#define  CCULED_CANADD6_GPIO_PIN 	 GPIO_Pin_13
#define  CCULED_CANADD6_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD6_GPIO,CCULED_CANADD6_GPIO_PIN)

#define  CCULED_CANADD7_RCC      	 RCC_AHB1Periph_GPIOF
#define  CCULED_CANADD7_GPIO 			 GPIOF
#define  CCULED_CANADD7_GPIO_PIN 	 GPIO_Pin_12
#define  CCULED_CANADD7_READ()		 GPIO_ReadInputDataBit(CCULED_CANADD7_GPIO,CCULED_CANADD7_GPIO_PIN)

void CCULED_CanAdd_Gpio_Init(void);
uint8_t CCULED_CanAddVal(void);

#endif //__CCU_LED_CANADDRES_H__
