#ifndef __MTD_MFD_CANADDRES_H__
#define __MTD_MFD_CANADDRES_H__


#include "stm32f4xx.h"
/*定义输入GPIO端口*/
#define  MTDMFD_CANADD0_RCC      	 RCC_AHB1Periph_GPIOC
#define  MTDMFD_CANADD0_GPIO 			 GPIOC
#define  MTDMFD_CANADD0_GPIO_PIN 	 GPIO_Pin_8
#define  MTDMFD_CANADD0_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD0_GPIO,MTDMFD_CANADD0_GPIO_PIN)

#define  MTDMFD_CANADD1_RCC      	 RCC_AHB1Periph_GPIOC
#define  MTDMFD_CANADD1_GPIO 			 GPIOC
#define  MTDMFD_CANADD1_GPIO_PIN 	 GPIO_Pin_7
#define  MTDMFD_CANADD1_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD1_GPIO,MTDMFD_CANADD1_GPIO_PIN)

#define  MTDMFD_CANADD2_RCC      	 RCC_AHB1Periph_GPIOC
#define  MTDMFD_CANADD2_GPIO 			 GPIOC
#define  MTDMFD_CANADD2_GPIO_PIN 	 GPIO_Pin_6
#define  MTDMFD_CANADD2_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD2_GPIO,MTDMFD_CANADD2_GPIO_PIN)

#define  MTDMFD_CANADD3_RCC      	 RCC_AHB1Periph_GPIOG
#define  MTDMFD_CANADD3_GPIO 			 GPIOG
#define  MTDMFD_CANADD3_GPIO_PIN 	 GPIO_Pin_8
#define  MTDMFD_CANADD3_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD3_GPIO,MTDMFD_CANADD3_GPIO_PIN)

#define  MTDMFD_CANADD4_RCC      	 RCC_AHB1Periph_GPIOA
#define  MTDMFD_CANADD4_GPIO 			 GPIOA
#define  MTDMFD_CANADD4_GPIO_PIN 	 GPIO_Pin_12
#define  MTDMFD_CANADD4_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD4_GPIO,MTDMFD_CANADD4_GPIO_PIN)

#define  MTDMFD_CANADD5_RCC      	 RCC_AHB1Periph_GPIOA
#define  MTDMFD_CANADD5_GPIO 			 GPIOA
#define  MTDMFD_CANADD5_GPIO_PIN 	 GPIO_Pin_11
#define  MTDMFD_CANADD5_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD5_GPIO,MTDMFD_CANADD5_GPIO_PIN)

#define  MTDMFD_CANADD6_RCC      	 RCC_AHB1Periph_GPIOA
#define  MTDMFD_CANADD6_GPIO 			 GPIOA
#define  MTDMFD_CANADD6_GPIO_PIN 	 GPIO_Pin_8
#define  MTDMFD_CANADD6_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD6_GPIO,MTDMFD_CANADD6_GPIO_PIN)

#define  MTDMFD_CANADD7_RCC      	 RCC_AHB1Periph_GPIOC
#define  MTDMFD_CANADD7_GPIO 			 GPIOC
#define  MTDMFD_CANADD7_GPIO_PIN 	 GPIO_Pin_9
#define  MTDMFD_CANADD7_READ()		 GPIO_ReadInputDataBit(MTDMFD_CANADD7_GPIO,MTDMFD_CANADD7_GPIO_PIN)

void MTDMFD_CanAdd_Gpio_Init(void);
uint8_t MTDMFD_CanAddVal(void);

#endif //__MTD_MFD_CANADDRES_H__
