#ifndef __VOLTAGEINPUT_H__
#define __VOLTAGEINPUT_H__

#include "stm32f4xx.h"

#define VOL110V_NUMBER         12    //110v电压输入个数
#define VOL24V_NUMBER       	 4	   //24v电压输入个数

#define VOLTAGE_110V_DI1_RCC         RCC_AHB1Periph_GPIOB
#define VOLTAGE_110V_DI1_GPIO        GPIOB
#define VOLTAGE_110V_DI1_GPIO_PIN    GPIO_Pin_12
#define VOLTAGE_110V_DI1_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI1_GPIO,VOLTAGE_110V_DI1_GPIO_PIN)

#define VOLTAGE_110V_DI2_RCC         RCC_AHB1Periph_GPIOE
#define VOLTAGE_110V_DI2_GPIO        GPIOE
#define VOLTAGE_110V_DI2_GPIO_PIN    GPIO_Pin_15
#define VOLTAGE_110V_DI2_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI2_GPIO,VOLTAGE_110V_DI2_GPIO_PIN)

#define VOLTAGE_110V_DI3_RCC         RCC_AHB1Periph_GPIOB
#define VOLTAGE_110V_DI3_GPIO        GPIOB
#define VOLTAGE_110V_DI3_GPIO_PIN    GPIO_Pin_15
#define VOLTAGE_110V_DI3_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI3_GPIO,VOLTAGE_110V_DI3_GPIO_PIN)

#define VOLTAGE_110V_DI4_RCC         RCC_AHB1Periph_GPIOB
#define VOLTAGE_110V_DI4_GPIO        GPIOB
#define VOLTAGE_110V_DI4_GPIO_PIN    GPIO_Pin_14
#define VOLTAGE_110V_DI4_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI4_GPIO,VOLTAGE_110V_DI4_GPIO_PIN)

#define VOLTAGE_110V_DI5_RCC         RCC_AHB1Periph_GPIOD
#define VOLTAGE_110V_DI5_GPIO        GPIOD
#define VOLTAGE_110V_DI5_GPIO_PIN    GPIO_Pin_9
#define VOLTAGE_110V_DI5_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI5_GPIO,VOLTAGE_110V_DI5_GPIO_PIN)

#define VOLTAGE_110V_DI6_RCC         RCC_AHB1Periph_GPIOD
#define VOLTAGE_110V_DI6_GPIO        GPIOD
#define VOLTAGE_110V_DI6_GPIO_PIN    GPIO_Pin_8
#define VOLTAGE_110V_DI6_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI6_GPIO,VOLTAGE_110V_DI6_GPIO_PIN)

#define VOLTAGE_110V_DI7_RCC         RCC_AHB1Periph_GPIOD
#define VOLTAGE_110V_DI7_GPIO        GPIOD
#define VOLTAGE_110V_DI7_GPIO_PIN    GPIO_Pin_11
#define VOLTAGE_110V_DI7_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI7_GPIO,VOLTAGE_110V_DI7_GPIO_PIN)

#define VOLTAGE_110V_DI8_RCC         RCC_AHB1Periph_GPIOD
#define VOLTAGE_110V_DI8_GPIO        GPIOD
#define VOLTAGE_110V_DI8_GPIO_PIN    GPIO_Pin_10
#define VOLTAGE_110V_DI8_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI8_GPIO,VOLTAGE_110V_DI8_GPIO_PIN)

#define VOLTAGE_110V_DI9_RCC         RCC_AHB1Periph_GPIOD
#define VOLTAGE_110V_DI9_GPIO        GPIOD
#define VOLTAGE_110V_DI9_GPIO_PIN    GPIO_Pin_13
#define VOLTAGE_110V_DI9_READ()    	 GPIO_ReadInputDataBit(VOLTAGE_110V_DI9_GPIO,VOLTAGE_110V_DI9_GPIO_PIN)

#define VOLTAGE_110V_DI10_RCC         RCC_AHB1Periph_GPIOD
#define VOLTAGE_110V_DI10_GPIO        GPIOD
#define VOLTAGE_110V_DI10_GPIO_PIN    GPIO_Pin_12
#define VOLTAGE_110V_DI10_READ()    	GPIO_ReadInputDataBit(VOLTAGE_110V_DI10_GPIO,VOLTAGE_110V_DI10_GPIO_PIN)

#define VOLTAGE_110V_DI11_RCC         RCC_AHB1Periph_GPIOG
#define VOLTAGE_110V_DI11_GPIO        GPIOG
#define VOLTAGE_110V_DI11_GPIO_PIN    GPIO_Pin_3
#define VOLTAGE_110V_DI11_READ()    	GPIO_ReadInputDataBit(VOLTAGE_110V_DI11_GPIO,VOLTAGE_110V_DI11_GPIO_PIN)

#define VOLTAGE_110V_DI12_RCC         RCC_AHB1Periph_GPIOG
#define VOLTAGE_110V_DI12_GPIO        GPIOG
#define VOLTAGE_110V_DI12_GPIO_PIN    GPIO_Pin_2
#define VOLTAGE_110V_DI12_READ()    	GPIO_ReadInputDataBit(VOLTAGE_110V_DI12_GPIO,VOLTAGE_110V_DI12_GPIO_PIN)


#define VOLTAGE_24V_DI1_RCC         RCC_AHB1Periph_GPIOG
#define VOLTAGE_24V_DI1_GPIO        GPIOG
#define VOLTAGE_24V_DI1_GPIO_PIN    GPIO_Pin_5
#define VOLTAGE_24V_DI1_READ()    	GPIO_ReadInputDataBit(VOLTAGE_24V_DI1_GPIO,VOLTAGE_24V_DI1_GPIO_PIN)

#define VOLTAGE_24V_DI2_RCC         RCC_AHB1Periph_GPIOG
#define VOLTAGE_24V_DI2_GPIO        GPIOG
#define VOLTAGE_24V_DI2_GPIO_PIN    GPIO_Pin_4
#define VOLTAGE_24V_DI2_READ()    	GPIO_ReadInputDataBit(VOLTAGE_24V_DI2_GPIO,VOLTAGE_24V_DI2_GPIO_PIN)


#define VOLTAGE_24V_DI3_RCC         RCC_AHB1Periph_GPIOG
#define VOLTAGE_24V_DI3_GPIO        GPIOG
#define VOLTAGE_24V_DI3_GPIO_PIN    GPIO_Pin_7
#define VOLTAGE_24V_DI3_READ()    	GPIO_ReadInputDataBit(VOLTAGE_24V_DI3_GPIO,VOLTAGE_24V_DI3_GPIO_PIN)

#define VOLTAGE_24V_DI4_RCC         RCC_AHB1Periph_GPIOG
#define VOLTAGE_24V_DI4_GPIO        GPIOG
#define VOLTAGE_24V_DI4_GPIO_PIN    GPIO_Pin_6
#define VOLTAGE_24V_DI4_READ()    	GPIO_ReadInputDataBit(VOLTAGE_24V_DI4_GPIO,VOLTAGE_24V_DI4_GPIO_PIN)


typedef struct{
    uint32_t     rcc;
    GPIO_TypeDef *gpio;
    uint16_t     pin;
//		void (* ReadState )(void);
}Voltage_Gpio_Info;


void Vol_110VGpio_Init(void);
void Vol_24VGpio_Init(void);

void Vol_110VRead_Scan(u8* DIBuf);
void Vol_24VRead_Scan(u8* DIBuf);
#endif //__VOLTAGEINPUT_H__

