
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS64 Masterdoor_mc1_1 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS64 Masterdoor_mc1_2 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS64 Masterdoor_T_1 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS64 Masterdoor_T_2 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS64 Masterdoor_M_1 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS64 Masterdoor_M_2 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS64 Masterdoor_T1_1 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS64 Masterdoor_T1_2 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS64 Masterdoor_T2_1 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS64 Masterdoor_T2_2 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS64 Masterdoor_mc2_1 = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
UNS64 Masterdoor_mc2_2 = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
UNS8 aaa[] =		/* Mapped at index 0x200C, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 0;

TIMER_HANDLE TestMaster_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x12D;	/* 301 */
                    subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t TestMaster_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[0] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[1] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[2] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[3] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[4] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[5] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[6] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[7] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestMaster_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t TestMaster_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestMaster_obj1006 = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 TestMaster_obj1014 = 0x80;	/* 128 */
                    subindex TestMaster_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1016[] = 
                    {
                      0x2012C	/* 131372 */
                    };
                    ODCallback_t TestMaster_Index1016_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestMaster_obj1017 = 0x64;	/* 100 */
                    ODCallback_t TestMaster_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x12345678;	/* 305419896 */
                    UNS32 TestMaster_obj1018_Product_Code = 0x90123456;	/* 2417112150 */
                    UNS32 TestMaster_obj1018_Revision_Number = 0x78901234;	/* 2022707764 */
                    UNS32 TestMaster_obj1018_Serial_Number = 0x56789012;	/* 1450741778 */
                    subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 TestMaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex TestMaster_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 TestMaster_obj1280_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex TestMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 TestMaster_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID_used_by_PDO = 0x283;	/* 643 */
                    UNS8 TestMaster_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID_used_by_PDO = 0x184;	/* 388 */
                    UNS8 TestMaster_obj1402_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1403_COB_ID_used_by_PDO = 0x284;	/* 644 */
                    UNS8 TestMaster_obj1403_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_SYNC_start_value }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1404_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 TestMaster_obj1404_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1404_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1404_SYNC_start_value }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1405_COB_ID_used_by_PDO = 0x285;	/* 645 */
                    UNS8 TestMaster_obj1405_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1405_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1405_SYNC_start_value }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1406_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 TestMaster_obj1406_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1406_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1406_SYNC_start_value }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1407_COB_ID_used_by_PDO = 0x286;	/* 646 */
                    UNS8 TestMaster_obj1407_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1407_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1407_SYNC_start_value }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1408 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1408_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 TestMaster_obj1408_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1408_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1408_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1408_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1408_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1408_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1408_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1408_SYNC_start_value }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1409 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1409_COB_ID_used_by_PDO = 0x287;	/* 647 */
                    UNS8 TestMaster_obj1409_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1409_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1409_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1409_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1409_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1409_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1409_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1409_SYNC_start_value }
                     };

/* index 0x140A :   Receive PDO 11 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj140A = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj140A_COB_ID_used_by_PDO = 0x188;	/* 392 */
                    UNS8 TestMaster_obj140A_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj140A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj140A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj140A_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj140A_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index140A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj140A },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj140A_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj140A_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj140A_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj140A_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj140A_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj140A_SYNC_start_value }
                     };

/* index 0x140B :   Receive PDO 12 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj140B = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj140B_COB_ID_used_by_PDO = 0x288;	/* 648 */
                    UNS8 TestMaster_obj140B_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestMaster_obj140B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj140B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj140B_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj140B_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index140B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj140B },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj140B_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj140B_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj140B_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj140B_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj140B_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj140B_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1600[] = 
                    {
                      0x20000040	/* 536870976 */
                    };
                    subindex TestMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1601[] = 
                    {
                      0x20010040	/* 536936512 */
                    };
                    subindex TestMaster_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[0] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1602[] = 
                    {
                      0x20020040	/* 537002048 */
                    };
                    subindex TestMaster_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[0] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1603[] = 
                    {
                      0x20030040	/* 537067584 */
                    };
                    subindex TestMaster_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[0] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1604 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1604[] = 
                    {
                      0x20040040	/* 537133120 */
                    };
                    subindex TestMaster_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1604[0] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1605 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1605[] = 
                    {
                      0x20050040	/* 537198656 */
                    };
                    subindex TestMaster_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1605[0] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1606 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1606[] = 
                    {
                      0x20060040	/* 537264192 */
                    };
                    subindex TestMaster_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1606[0] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1607 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1607[] = 
                    {
                      0x20070040	/* 537329728 */
                    };
                    subindex TestMaster_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1607[0] }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1608 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1608[] = 
                    {
                      0x20080040	/* 537395264 */
                    };
                    subindex TestMaster_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1608 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1608[0] }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1609 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1609[] = 
                    {
                      0x20090040	/* 537460800 */
                    };
                    subindex TestMaster_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1609 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1609[0] }
                     };

/* index 0x160A :   Receive PDO 11 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj160A = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj160A[] = 
                    {
                      0x200A0040	/* 537526336 */
                    };
                    subindex TestMaster_Index160A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj160A },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj160A[0] }
                     };

/* index 0x160B :   Receive PDO 12 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj160B = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj160B[] = 
                    {
                      0x200B0040	/* 537591872 */
                    };
                    subindex TestMaster_Index160B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj160B },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj160B[0] }
                     };

/* index 0x2000 :   Mapped variable Masterdoor-mc1-1 */
                    ODCallback_t Masterdoor_mc1_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2000[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_mc1_1 }
                     };

/* index 0x2001 :   Mapped variable Masterdoor-mc1-2 */
                    ODCallback_t Masterdoor_mc1_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2001[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_mc1_2 }
                     };

/* index 0x2002 :   Mapped variable Masterdoor-T-1 */
                    ODCallback_t Masterdoor_T_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2002[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_T_1 }
                     };

/* index 0x2003 :   Mapped variable Masterdoor-T-2 */
                    ODCallback_t Masterdoor_T_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2003[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_T_2 }
                     };

/* index 0x2004 :   Mapped variable Masterdoor-M-1 */
                    ODCallback_t Masterdoor_M_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2004[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_M_1 }
                     };

/* index 0x2005 :   Mapped variable Masterdoor-M-2 */
                    ODCallback_t Masterdoor_M_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2005[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_M_2 }
                     };

/* index 0x2006 :   Mapped variable Masterdoor-T1-1 */
                    subindex TestMaster_Index2006[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_T1_1 }
                     };

/* index 0x2007 :   Mapped variable Masterdoor-T1-2 */
                    subindex TestMaster_Index2007[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_T1_2 }
                     };

/* index 0x2008 :   Mapped variable Masterdoor-T2-1 */
                    subindex TestMaster_Index2008[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_T2_1 }
                     };

/* index 0x2009 :   Mapped variable Masterdoor-T2-2 */
                    subindex TestMaster_Index2009[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_T2_2 }
                     };

/* index 0x200A :   Mapped variable Masterdoor-mc2-1 */
                    subindex TestMaster_Index200A[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_mc2_1 }
                     };

/* index 0x200B :   Mapped variable Masterdoor-mc2-2 */
                    subindex TestMaster_Index200B[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Masterdoor_mc2_2 }
                     };

/* index 0x200C :   Mapped variable aaa */
                    UNS8 TestMaster_highestSubIndex_obj200C = 1; /* number of subindex - 1*/
                    subindex TestMaster_Index200C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj200C },
                       { RW, uint8, sizeof (UNS8), (void*)&aaa[0] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestMaster_objdict[] = 
{
  { (subindex*)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
  { (subindex*)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
  { (subindex*)TestMaster_Index1003,sizeof(TestMaster_Index1003)/sizeof(TestMaster_Index1003[0]), 0x1003},
  { (subindex*)TestMaster_Index1005,sizeof(TestMaster_Index1005)/sizeof(TestMaster_Index1005[0]), 0x1005},
  { (subindex*)TestMaster_Index1006,sizeof(TestMaster_Index1006)/sizeof(TestMaster_Index1006[0]), 0x1006},
  { (subindex*)TestMaster_Index1014,sizeof(TestMaster_Index1014)/sizeof(TestMaster_Index1014[0]), 0x1014},
  { (subindex*)TestMaster_Index1016,sizeof(TestMaster_Index1016)/sizeof(TestMaster_Index1016[0]), 0x1016},
  { (subindex*)TestMaster_Index1017,sizeof(TestMaster_Index1017)/sizeof(TestMaster_Index1017[0]), 0x1017},
  { (subindex*)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},
  { (subindex*)TestMaster_Index1200,sizeof(TestMaster_Index1200)/sizeof(TestMaster_Index1200[0]), 0x1200},
  { (subindex*)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
  { (subindex*)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
  { (subindex*)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
  { (subindex*)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
  { (subindex*)TestMaster_Index1403,sizeof(TestMaster_Index1403)/sizeof(TestMaster_Index1403[0]), 0x1403},
  { (subindex*)TestMaster_Index1404,sizeof(TestMaster_Index1404)/sizeof(TestMaster_Index1404[0]), 0x1404},
  { (subindex*)TestMaster_Index1405,sizeof(TestMaster_Index1405)/sizeof(TestMaster_Index1405[0]), 0x1405},
  { (subindex*)TestMaster_Index1406,sizeof(TestMaster_Index1406)/sizeof(TestMaster_Index1406[0]), 0x1406},
  { (subindex*)TestMaster_Index1407,sizeof(TestMaster_Index1407)/sizeof(TestMaster_Index1407[0]), 0x1407},
  { (subindex*)TestMaster_Index1408,sizeof(TestMaster_Index1408)/sizeof(TestMaster_Index1408[0]), 0x1408},
  { (subindex*)TestMaster_Index1409,sizeof(TestMaster_Index1409)/sizeof(TestMaster_Index1409[0]), 0x1409},
  { (subindex*)TestMaster_Index140A,sizeof(TestMaster_Index140A)/sizeof(TestMaster_Index140A[0]), 0x140A},
  { (subindex*)TestMaster_Index140B,sizeof(TestMaster_Index140B)/sizeof(TestMaster_Index140B[0]), 0x140B},
  { (subindex*)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
  { (subindex*)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
  { (subindex*)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
  { (subindex*)TestMaster_Index1603,sizeof(TestMaster_Index1603)/sizeof(TestMaster_Index1603[0]), 0x1603},
  { (subindex*)TestMaster_Index1604,sizeof(TestMaster_Index1604)/sizeof(TestMaster_Index1604[0]), 0x1604},
  { (subindex*)TestMaster_Index1605,sizeof(TestMaster_Index1605)/sizeof(TestMaster_Index1605[0]), 0x1605},
  { (subindex*)TestMaster_Index1606,sizeof(TestMaster_Index1606)/sizeof(TestMaster_Index1606[0]), 0x1606},
  { (subindex*)TestMaster_Index1607,sizeof(TestMaster_Index1607)/sizeof(TestMaster_Index1607[0]), 0x1607},
  { (subindex*)TestMaster_Index1608,sizeof(TestMaster_Index1608)/sizeof(TestMaster_Index1608[0]), 0x1608},
  { (subindex*)TestMaster_Index1609,sizeof(TestMaster_Index1609)/sizeof(TestMaster_Index1609[0]), 0x1609},
  { (subindex*)TestMaster_Index160A,sizeof(TestMaster_Index160A)/sizeof(TestMaster_Index160A[0]), 0x160A},
  { (subindex*)TestMaster_Index160B,sizeof(TestMaster_Index160B)/sizeof(TestMaster_Index160B[0]), 0x160B},
  { (subindex*)TestMaster_Index2000,sizeof(TestMaster_Index2000)/sizeof(TestMaster_Index2000[0]), 0x2000},
  { (subindex*)TestMaster_Index2001,sizeof(TestMaster_Index2001)/sizeof(TestMaster_Index2001[0]), 0x2001},
  { (subindex*)TestMaster_Index2002,sizeof(TestMaster_Index2002)/sizeof(TestMaster_Index2002[0]), 0x2002},
  { (subindex*)TestMaster_Index2003,sizeof(TestMaster_Index2003)/sizeof(TestMaster_Index2003[0]), 0x2003},
  { (subindex*)TestMaster_Index2004,sizeof(TestMaster_Index2004)/sizeof(TestMaster_Index2004[0]), 0x2004},
  { (subindex*)TestMaster_Index2005,sizeof(TestMaster_Index2005)/sizeof(TestMaster_Index2005[0]), 0x2005},
  { (subindex*)TestMaster_Index2006,sizeof(TestMaster_Index2006)/sizeof(TestMaster_Index2006[0]), 0x2006},
  { (subindex*)TestMaster_Index2007,sizeof(TestMaster_Index2007)/sizeof(TestMaster_Index2007[0]), 0x2007},
  { (subindex*)TestMaster_Index2008,sizeof(TestMaster_Index2008)/sizeof(TestMaster_Index2008[0]), 0x2008},
  { (subindex*)TestMaster_Index2009,sizeof(TestMaster_Index2009)/sizeof(TestMaster_Index2009[0]), 0x2009},
  { (subindex*)TestMaster_Index200A,sizeof(TestMaster_Index200A)/sizeof(TestMaster_Index200A[0]), 0x200A},
  { (subindex*)TestMaster_Index200B,sizeof(TestMaster_Index200B)/sizeof(TestMaster_Index200B[0]), 0x200B},
  { (subindex*)TestMaster_Index200C,sizeof(TestMaster_Index200C)/sizeof(TestMaster_Index200C[0]), 0x200C},
};

const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;*callbacks = TestMaster_Index1003_callbacks; break;
		case 0x1005: i = 3;*callbacks = TestMaster_Index1005_callbacks; break;
		case 0x1006: i = 4;*callbacks = TestMaster_Index1006_callbacks; break;
		case 0x1014: i = 5;break;
		case 0x1016: i = 6;*callbacks = TestMaster_Index1016_callbacks; break;
		case 0x1017: i = 7;*callbacks = TestMaster_Index1017_callbacks; break;
		case 0x1018: i = 8;break;
		case 0x1200: i = 9;break;
		case 0x1280: i = 10;break;
		case 0x1400: i = 11;break;
		case 0x1401: i = 12;break;
		case 0x1402: i = 13;break;
		case 0x1403: i = 14;break;
		case 0x1404: i = 15;break;
		case 0x1405: i = 16;break;
		case 0x1406: i = 17;break;
		case 0x1407: i = 18;break;
		case 0x1408: i = 19;break;
		case 0x1409: i = 20;break;
		case 0x140A: i = 21;break;
		case 0x140B: i = 22;break;
		case 0x1600: i = 23;break;
		case 0x1601: i = 24;break;
		case 0x1602: i = 25;break;
		case 0x1603: i = 26;break;
		case 0x1604: i = 27;break;
		case 0x1605: i = 28;break;
		case 0x1606: i = 29;break;
		case 0x1607: i = 30;break;
		case 0x1608: i = 31;break;
		case 0x1609: i = 32;break;
		case 0x160A: i = 33;break;
		case 0x160B: i = 34;break;
		case 0x2000: i = 35;*callbacks = Masterdoor_mc1_1_callbacks; break;
		case 0x2001: i = 36;*callbacks = Masterdoor_mc1_2_callbacks; break;
		case 0x2002: i = 37;*callbacks = Masterdoor_T_1_callbacks; break;
		case 0x2003: i = 38;*callbacks = Masterdoor_T_2_callbacks; break;
		case 0x2004: i = 39;*callbacks = Masterdoor_M_1_callbacks; break;
		case 0x2005: i = 40;*callbacks = Masterdoor_M_2_callbacks; break;
		case 0x2006: i = 41;break;
		case 0x2007: i = 42;break;
		case 0x2008: i = 43;break;
		case 0x2009: i = 44;break;
		case 0x200A: i = 45;break;
		case 0x200B: i = 46;break;
		case 0x200C: i = 47;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaster_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index TestMaster_firstIndex = {
  9, /* SDO_SVR */
  10, /* SDO_CLT */
  11, /* PDO_RCV */
  23, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index TestMaster_lastIndex = {
  9, /* SDO_SVR */
  10, /* SDO_CLT */
  22, /* PDO_RCV */
  34, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

