
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASTER_H
#define TESTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;
extern UNS64 Masterdoor_mc1_1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS64 Masterdoor_mc1_2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS64 Masterdoor_T_1;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS64 Masterdoor_T_2;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS64 Masterdoor_M_1;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS64 Masterdoor_M_2;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS64 Masterdoor_T1_1;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS64 Masterdoor_T1_2;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS64 Masterdoor_T2_1;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS64 Masterdoor_T2_2;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS64 Masterdoor_mc2_1;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS64 Masterdoor_mc2_2;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS8 aaa[1];		/* Mapped at index 0x200C, subindex 0x01 - 0x01 */

#endif // TESTMASTER_H
