
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestSlave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS64 door_mc1_1 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS64 door_mc1_2 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS64 door_T_1 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS64 door_T_2 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS64 door_M_1 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS64 door_M_2 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS64 door_T1_1 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS64 door_T1_2 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS64 door_T2_1 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS64 door_T2_2 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS64 door_mc2_1 = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
UNS64 door_mc2_2 = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestSlave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestSlave_iam_a_slave = 1;

TIMER_HANDLE TestSlave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestSlave_obj1000 = 0x12D;	/* 301 */
                    subindex TestSlave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestSlave_obj1001 = 0x0;	/* 0 */
                    subindex TestSlave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 TestSlave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t TestSlave_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[0] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[1] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[2] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[3] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[4] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[5] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[6] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[7] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestSlave_obj1005 = 0x80;	/* 128 */
                    ODCallback_t TestSlave_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestSlave_obj1006 = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 TestSlave_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestSlave_obj100D = 0x0;   /* 0 */

/* index 0x1010 :   Store parameters. */
                    UNS8 TestSlave_highestSubIndex_obj1010 = 4; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1010_Save_Manufacturer_Parameters_1 = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1010_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1010_Save_Communication_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1010_Save_Application_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1010_Save_Manufacturer_Parameters_1 }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 TestSlave_highestSubIndex_obj1011 = 4; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1011_Restore_Application_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1011_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1011_Restore_Communication_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1011_Restore_Application_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 TestSlave_obj1014 = 0x80;	/* 128 */
                    ODCallback_t TestSlave_Index1014_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestSlave_highestSubIndex_obj1016 = 0;
                    UNS32 TestSlave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestSlave_obj1017 = 0x64;	/* 100 */
                    ODCallback_t TestSlave_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestSlave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1018_Vendor_ID = 0x12345678;	/* 305419896 */
                    UNS32 TestSlave_obj1018_Product_Code = 0x90123456;	/* 2417112150 */
                    UNS32 TestSlave_obj1018_Revision_Number = 0x78901234;	/* 2022707764 */
                    UNS32 TestSlave_obj1018_Serial_Number = 0x56789012;	/* 1450741778 */
                    subindex TestSlave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 TestSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex TestSlave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1400_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 TestSlave_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1401_COB_ID_used_by_PDO = 0x283;	/* 643 */
                    UNS8 TestSlave_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1402_COB_ID_used_by_PDO = 0x184;	/* 388 */
                    UNS8 TestSlave_obj1402_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1403_COB_ID_used_by_PDO = 0x284;	/* 644 */
                    UNS8 TestSlave_obj1403_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_SYNC_start_value }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1404_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 TestSlave_obj1404_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1404_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1404_SYNC_start_value }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1405_COB_ID_used_by_PDO = 0x285;	/* 645 */
                    UNS8 TestSlave_obj1405_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1405_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1405_SYNC_start_value }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1406_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 TestSlave_obj1406_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1406_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1406_SYNC_start_value }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1407_COB_ID_used_by_PDO = 0x286;	/* 646 */
                    UNS8 TestSlave_obj1407_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1407_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1407_SYNC_start_value }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1408 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1408_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 TestSlave_obj1408_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1408_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1408_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1408_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1408_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1408_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1408_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1408_SYNC_start_value }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1409 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1409_COB_ID_used_by_PDO = 0x287;	/* 647 */
                    UNS8 TestSlave_obj1409_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1409_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1409_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1409_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1409_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1409_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1409_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1409_SYNC_start_value }
                     };

/* index 0x140A :   Receive PDO 11 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj140A = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj140A_COB_ID_used_by_PDO = 0x188;	/* 392 */
                    UNS8 TestSlave_obj140A_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj140A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj140A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj140A_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj140A_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index140A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj140A },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj140A_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj140A_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj140A_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj140A_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj140A_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj140A_SYNC_start_value }
                     };

/* index 0x140B :   Receive PDO 12 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj140B = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj140B_COB_ID_used_by_PDO = 0x288;	/* 648 */
                    UNS8 TestSlave_obj140B_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj140B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj140B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj140B_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj140B_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index140B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj140B },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj140B_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj140B_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj140B_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj140B_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj140B_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj140B_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1600[] = 
                    {
                      0x20000040	/* 536870976 */
                    };
                    subindex TestSlave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1601[] = 
                    {
                      0x20010040	/* 536936512 */
                    };
                    subindex TestSlave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1601[0] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1602[] = 
                    {
                      0x20020040	/* 537002048 */
                    };
                    subindex TestSlave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[0] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1603[] = 
                    {
                      0x20030040	/* 537067584 */
                    };
                    subindex TestSlave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[0] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1604 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1604[] = 
                    {
                      0x20040040	/* 537133120 */
                    };
                    subindex TestSlave_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1604[0] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1605 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1605[] = 
                    {
                      0x20050040	/* 537198656 */
                    };
                    subindex TestSlave_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1605[0] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1606 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1606[] = 
                    {
                      0x20060040	/* 537264192 */
                    };
                    subindex TestSlave_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1606[0] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1607 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1607[] = 
                    {
                      0x20070040	/* 537329728 */
                    };
                    subindex TestSlave_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1607[0] }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1608 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1608[] = 
                    {
                      0x20080040	/* 537395264 */
                    };
                    subindex TestSlave_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1608 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1608[0] }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1609 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1609[] = 
                    {
                      0x20090040	/* 537460800 */
                    };
                    subindex TestSlave_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1609 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1609[0] }
                     };

/* index 0x160A :   Receive PDO 11 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj160A = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj160A[] = 
                    {
                      0x200A0040	/* 537526336 */
                    };
                    subindex TestSlave_Index160A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj160A },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj160A[0] }
                     };

/* index 0x160B :   Receive PDO 12 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj160B = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj160B[] = 
                    {
                      0x200B0040	/* 537591872 */
                    };
                    subindex TestSlave_Index160B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj160B },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj160B[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1800_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 TestSlave_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1800_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1800_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1800_COB_ID_used_by_PDO },
                       { RW|TO_BE_SAVE, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_Transmission_Type },
                       { RW|TO_BE_SAVE, uint16, sizeof (UNS16), (void*)&TestSlave_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1801_COB_ID_used_by_PDO = 0x283;	/* 643 */
                    UNS8 TestSlave_obj1801_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1801_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1801_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1802_COB_ID_used_by_PDO = 0x184;	/* 388 */
                    UNS8 TestSlave_obj1802_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1802_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1802_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1803_COB_ID_used_by_PDO = 0x284;	/* 644 */
                    UNS8 TestSlave_obj1803_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1803_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1803_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_SYNC_start_value }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1804 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1804_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 TestSlave_obj1804_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1804_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1804_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1804_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1804_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1804[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1804 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1804_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1804_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1804_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1804_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1804_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1804_SYNC_start_value }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1805 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1805_COB_ID_used_by_PDO = 0x285;	/* 645 */
                    UNS8 TestSlave_obj1805_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1805_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1805_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1805_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1805_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1805[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1805 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1805_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1805_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1805_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1805_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1805_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1805_SYNC_start_value }
                     };

/* index 0x1806 :   Transmit PDO 7 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1806 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1806_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 TestSlave_obj1806_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1806_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1806_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1806_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1806_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1806_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1806[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1806 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1806_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1806_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1806_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1806_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1806_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1806_SYNC_start_value }
                     };

/* index 0x1807 :   Transmit PDO 8 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1807 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1807_COB_ID_used_by_PDO = 0x286;	/* 646 */
                    UNS8 TestSlave_obj1807_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1807_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1807_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1807_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1807_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1807_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1807[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1807 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1807_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1807_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1807_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1807_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1807_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1807_SYNC_start_value }
                     };

/* index 0x1808 :   Transmit PDO 9 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1808 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1808_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 TestSlave_obj1808_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1808_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1808_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1808_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1808_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1808_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1808[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1808 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1808_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1808_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1808_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1808_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1808_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1808_SYNC_start_value }
                     };

/* index 0x1809 :   Transmit PDO 10 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1809 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1809_COB_ID_used_by_PDO = 0x287;	/* 647 */
                    UNS8 TestSlave_obj1809_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj1809_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj1809_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1809_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj1809_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1809_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1809[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1809 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1809_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1809_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1809_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1809_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1809_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1809_SYNC_start_value }
                     };

/* index 0x180A :   Transmit PDO 11 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj180A = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj180A_COB_ID_used_by_PDO = 0x188;	/* 392 */
                    UNS8 TestSlave_obj180A_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj180A_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj180A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj180A_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj180A_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index180A_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index180A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj180A },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj180A_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj180A_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj180A_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj180A_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj180A_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj180A_SYNC_start_value }
                     };

/* index 0x180B :   Transmit PDO 12 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj180B = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj180B_COB_ID_used_by_PDO = 0x288;	/* 648 */
                    UNS8 TestSlave_obj180B_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TestSlave_obj180B_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestSlave_obj180B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj180B_Event_Timer = 0x1388;	/* 5000 */
                    UNS8 TestSlave_obj180B_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index180B_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index180B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj180B },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj180B_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj180B_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj180B_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj180B_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj180B_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj180B_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A00[] = 
                    {
                      0x20000040	/* 536870976 */
                    };
                    subindex TestSlave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A00[0] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A01 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A01[] = 
                    {
                      0x20010040	/* 536936512 */
                    };
                    subindex TestSlave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A01[0] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A02[] = 
                    {
                      0x20020040	/* 537002048 */
                    };
                    ODCallback_t TestSlave_Index1A02_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A02[0] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A03 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A03[] = 
                    {
                      0x20030040	/* 537067584 */
                    };
                    ODCallback_t TestSlave_Index1A03_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A03[0] }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A04 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A04[] = 
                    {
                      0x20040040	/* 537133120 */
                    };
                    ODCallback_t TestSlave_Index1A04_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1A04[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A04 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A04[0] }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A05 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A05[] = 
                    {
                      0x20050040	/* 537198656 */
                    };
                    ODCallback_t TestSlave_Index1A05_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1A05[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A05 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A05[0] }
                     };

/* index 0x1A06 :   Transmit PDO 7 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A06 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A06[] = 
                    {
                      0x20060040	/* 537264192 */
                    };
                    subindex TestSlave_Index1A06[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A06 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A06[0] }
                     };

/* index 0x1A07 :   Transmit PDO 8 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A07 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A07[] = 
                    {
                      0x20070040	/* 537329728 */
                    };
                    subindex TestSlave_Index1A07[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A07 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A07[0] }
                     };

/* index 0x1A08 :   Transmit PDO 9 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A08 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A08[] = 
                    {
                      0x20080040	/* 537395264 */
                    };
                    subindex TestSlave_Index1A08[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A08 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A08[0] }
                     };

/* index 0x1A09 :   Transmit PDO 10 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A09 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A09[] = 
                    {
                      0x20090040	/* 537460800 */
                    };
                    subindex TestSlave_Index1A09[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A09 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A09[0] }
                     };

/* index 0x1A0A :   Transmit PDO 11 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A0A = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A0A[] = 
                    {
                      0x200A0040	/* 537526336 */
                    };
                    subindex TestSlave_Index1A0A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A0A },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A0A[0] }
                     };

/* index 0x1A0B :   Transmit PDO 12 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A0B = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A0B[] = 
                    {
                      0x200B0040	/* 537591872 */
                    };
                    subindex TestSlave_Index1A0B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A0B },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A0B[0] }
                     };

/* index 0x2000 :   Mapped variable door-mc1-1 */
                    ODCallback_t door_mc1_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2000[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_mc1_1 }
                     };

/* index 0x2001 :   Mapped variable door-mc1-2 */
                    ODCallback_t door_mc1_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2001[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_mc1_2 }
                     };

/* index 0x2002 :   Mapped variable door-T-1 */
                    ODCallback_t door_T_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2002[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_T_1 }
                     };

/* index 0x2003 :   Mapped variable door-T-2 */
                    ODCallback_t door_T_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2003[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_T_2 }
                     };

/* index 0x2004 :   Mapped variable door-M-1 */
                    ODCallback_t door_M_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2004[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_M_1 }
                     };

/* index 0x2005 :   Mapped variable door-M-2 */
                    ODCallback_t door_M_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2005[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_M_2 }
                     };

/* index 0x2006 :   Mapped variable door-T1-1 */
                    ODCallback_t door_T1_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2006[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_T1_1 }
                     };

/* index 0x2007 :   Mapped variable door-T1-2 */
                    ODCallback_t door_T1_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2007[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_T1_2 }
                     };

/* index 0x2008 :   Mapped variable door-T2-1 */
                    ODCallback_t door_T2_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2008[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_T2_1 }
                     };

/* index 0x2009 :   Mapped variable door-T2-2 */
                    ODCallback_t door_T2_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index2009[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_T2_2 }
                     };

/* index 0x200A :   Mapped variable door-mc2-1 */
                    ODCallback_t door_mc2_1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index200A[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_mc2_1 }
                     };

/* index 0x200B :   Mapped variable door-mc2-2 */
                    ODCallback_t door_mc2_2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index200B[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&door_mc2_2 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestSlave_objdict[] = 
{
  { (subindex*)TestSlave_Index1000,sizeof(TestSlave_Index1000)/sizeof(TestSlave_Index1000[0]), 0x1000},
  { (subindex*)TestSlave_Index1001,sizeof(TestSlave_Index1001)/sizeof(TestSlave_Index1001[0]), 0x1001},
  { (subindex*)TestSlave_Index1003,sizeof(TestSlave_Index1003)/sizeof(TestSlave_Index1003[0]), 0x1003},
  { (subindex*)TestSlave_Index1005,sizeof(TestSlave_Index1005)/sizeof(TestSlave_Index1005[0]), 0x1005},
  { (subindex*)TestSlave_Index1006,sizeof(TestSlave_Index1006)/sizeof(TestSlave_Index1006[0]), 0x1006},
  { (subindex*)TestSlave_Index1010,sizeof(TestSlave_Index1010)/sizeof(TestSlave_Index1010[0]), 0x1010},
  { (subindex*)TestSlave_Index1011,sizeof(TestSlave_Index1011)/sizeof(TestSlave_Index1011[0]), 0x1011},
  { (subindex*)TestSlave_Index1014,sizeof(TestSlave_Index1014)/sizeof(TestSlave_Index1014[0]), 0x1014},
  { (subindex*)TestSlave_Index1017,sizeof(TestSlave_Index1017)/sizeof(TestSlave_Index1017[0]), 0x1017},
  { (subindex*)TestSlave_Index1018,sizeof(TestSlave_Index1018)/sizeof(TestSlave_Index1018[0]), 0x1018},
  { (subindex*)TestSlave_Index1200,sizeof(TestSlave_Index1200)/sizeof(TestSlave_Index1200[0]), 0x1200},
  { (subindex*)TestSlave_Index1400,sizeof(TestSlave_Index1400)/sizeof(TestSlave_Index1400[0]), 0x1400},
  { (subindex*)TestSlave_Index1401,sizeof(TestSlave_Index1401)/sizeof(TestSlave_Index1401[0]), 0x1401},
  { (subindex*)TestSlave_Index1402,sizeof(TestSlave_Index1402)/sizeof(TestSlave_Index1402[0]), 0x1402},
  { (subindex*)TestSlave_Index1403,sizeof(TestSlave_Index1403)/sizeof(TestSlave_Index1403[0]), 0x1403},
  { (subindex*)TestSlave_Index1404,sizeof(TestSlave_Index1404)/sizeof(TestSlave_Index1404[0]), 0x1404},
  { (subindex*)TestSlave_Index1405,sizeof(TestSlave_Index1405)/sizeof(TestSlave_Index1405[0]), 0x1405},
  { (subindex*)TestSlave_Index1406,sizeof(TestSlave_Index1406)/sizeof(TestSlave_Index1406[0]), 0x1406},
  { (subindex*)TestSlave_Index1407,sizeof(TestSlave_Index1407)/sizeof(TestSlave_Index1407[0]), 0x1407},
  { (subindex*)TestSlave_Index1408,sizeof(TestSlave_Index1408)/sizeof(TestSlave_Index1408[0]), 0x1408},
  { (subindex*)TestSlave_Index1409,sizeof(TestSlave_Index1409)/sizeof(TestSlave_Index1409[0]), 0x1409},
  { (subindex*)TestSlave_Index140A,sizeof(TestSlave_Index140A)/sizeof(TestSlave_Index140A[0]), 0x140A},
  { (subindex*)TestSlave_Index140B,sizeof(TestSlave_Index140B)/sizeof(TestSlave_Index140B[0]), 0x140B},
  { (subindex*)TestSlave_Index1600,sizeof(TestSlave_Index1600)/sizeof(TestSlave_Index1600[0]), 0x1600},
  { (subindex*)TestSlave_Index1601,sizeof(TestSlave_Index1601)/sizeof(TestSlave_Index1601[0]), 0x1601},
  { (subindex*)TestSlave_Index1602,sizeof(TestSlave_Index1602)/sizeof(TestSlave_Index1602[0]), 0x1602},
  { (subindex*)TestSlave_Index1603,sizeof(TestSlave_Index1603)/sizeof(TestSlave_Index1603[0]), 0x1603},
  { (subindex*)TestSlave_Index1604,sizeof(TestSlave_Index1604)/sizeof(TestSlave_Index1604[0]), 0x1604},
  { (subindex*)TestSlave_Index1605,sizeof(TestSlave_Index1605)/sizeof(TestSlave_Index1605[0]), 0x1605},
  { (subindex*)TestSlave_Index1606,sizeof(TestSlave_Index1606)/sizeof(TestSlave_Index1606[0]), 0x1606},
  { (subindex*)TestSlave_Index1607,sizeof(TestSlave_Index1607)/sizeof(TestSlave_Index1607[0]), 0x1607},
  { (subindex*)TestSlave_Index1608,sizeof(TestSlave_Index1608)/sizeof(TestSlave_Index1608[0]), 0x1608},
  { (subindex*)TestSlave_Index1609,sizeof(TestSlave_Index1609)/sizeof(TestSlave_Index1609[0]), 0x1609},
  { (subindex*)TestSlave_Index160A,sizeof(TestSlave_Index160A)/sizeof(TestSlave_Index160A[0]), 0x160A},
  { (subindex*)TestSlave_Index160B,sizeof(TestSlave_Index160B)/sizeof(TestSlave_Index160B[0]), 0x160B},
  { (subindex*)TestSlave_Index1800,sizeof(TestSlave_Index1800)/sizeof(TestSlave_Index1800[0]), 0x1800},
  { (subindex*)TestSlave_Index1801,sizeof(TestSlave_Index1801)/sizeof(TestSlave_Index1801[0]), 0x1801},
  { (subindex*)TestSlave_Index1802,sizeof(TestSlave_Index1802)/sizeof(TestSlave_Index1802[0]), 0x1802},
  { (subindex*)TestSlave_Index1803,sizeof(TestSlave_Index1803)/sizeof(TestSlave_Index1803[0]), 0x1803},
  { (subindex*)TestSlave_Index1804,sizeof(TestSlave_Index1804)/sizeof(TestSlave_Index1804[0]), 0x1804},
  { (subindex*)TestSlave_Index1805,sizeof(TestSlave_Index1805)/sizeof(TestSlave_Index1805[0]), 0x1805},
  { (subindex*)TestSlave_Index1806,sizeof(TestSlave_Index1806)/sizeof(TestSlave_Index1806[0]), 0x1806},
  { (subindex*)TestSlave_Index1807,sizeof(TestSlave_Index1807)/sizeof(TestSlave_Index1807[0]), 0x1807},
  { (subindex*)TestSlave_Index1808,sizeof(TestSlave_Index1808)/sizeof(TestSlave_Index1808[0]), 0x1808},
  { (subindex*)TestSlave_Index1809,sizeof(TestSlave_Index1809)/sizeof(TestSlave_Index1809[0]), 0x1809},
  { (subindex*)TestSlave_Index180A,sizeof(TestSlave_Index180A)/sizeof(TestSlave_Index180A[0]), 0x180A},
  { (subindex*)TestSlave_Index180B,sizeof(TestSlave_Index180B)/sizeof(TestSlave_Index180B[0]), 0x180B},
  { (subindex*)TestSlave_Index1A00,sizeof(TestSlave_Index1A00)/sizeof(TestSlave_Index1A00[0]), 0x1A00},
  { (subindex*)TestSlave_Index1A01,sizeof(TestSlave_Index1A01)/sizeof(TestSlave_Index1A01[0]), 0x1A01},
  { (subindex*)TestSlave_Index1A02,sizeof(TestSlave_Index1A02)/sizeof(TestSlave_Index1A02[0]), 0x1A02},
  { (subindex*)TestSlave_Index1A03,sizeof(TestSlave_Index1A03)/sizeof(TestSlave_Index1A03[0]), 0x1A03},
  { (subindex*)TestSlave_Index1A04,sizeof(TestSlave_Index1A04)/sizeof(TestSlave_Index1A04[0]), 0x1A04},
  { (subindex*)TestSlave_Index1A05,sizeof(TestSlave_Index1A05)/sizeof(TestSlave_Index1A05[0]), 0x1A05},
  { (subindex*)TestSlave_Index1A06,sizeof(TestSlave_Index1A06)/sizeof(TestSlave_Index1A06[0]), 0x1A06},
  { (subindex*)TestSlave_Index1A07,sizeof(TestSlave_Index1A07)/sizeof(TestSlave_Index1A07[0]), 0x1A07},
  { (subindex*)TestSlave_Index1A08,sizeof(TestSlave_Index1A08)/sizeof(TestSlave_Index1A08[0]), 0x1A08},
  { (subindex*)TestSlave_Index1A09,sizeof(TestSlave_Index1A09)/sizeof(TestSlave_Index1A09[0]), 0x1A09},
  { (subindex*)TestSlave_Index1A0A,sizeof(TestSlave_Index1A0A)/sizeof(TestSlave_Index1A0A[0]), 0x1A0A},
  { (subindex*)TestSlave_Index1A0B,sizeof(TestSlave_Index1A0B)/sizeof(TestSlave_Index1A0B[0]), 0x1A0B},
  { (subindex*)TestSlave_Index2000,sizeof(TestSlave_Index2000)/sizeof(TestSlave_Index2000[0]), 0x2000},
  { (subindex*)TestSlave_Index2001,sizeof(TestSlave_Index2001)/sizeof(TestSlave_Index2001[0]), 0x2001},
  { (subindex*)TestSlave_Index2002,sizeof(TestSlave_Index2002)/sizeof(TestSlave_Index2002[0]), 0x2002},
  { (subindex*)TestSlave_Index2003,sizeof(TestSlave_Index2003)/sizeof(TestSlave_Index2003[0]), 0x2003},
  { (subindex*)TestSlave_Index2004,sizeof(TestSlave_Index2004)/sizeof(TestSlave_Index2004[0]), 0x2004},
  { (subindex*)TestSlave_Index2005,sizeof(TestSlave_Index2005)/sizeof(TestSlave_Index2005[0]), 0x2005},
  { (subindex*)TestSlave_Index2006,sizeof(TestSlave_Index2006)/sizeof(TestSlave_Index2006[0]), 0x2006},
  { (subindex*)TestSlave_Index2007,sizeof(TestSlave_Index2007)/sizeof(TestSlave_Index2007[0]), 0x2007},
  { (subindex*)TestSlave_Index2008,sizeof(TestSlave_Index2008)/sizeof(TestSlave_Index2008[0]), 0x2008},
  { (subindex*)TestSlave_Index2009,sizeof(TestSlave_Index2009)/sizeof(TestSlave_Index2009[0]), 0x2009},
  { (subindex*)TestSlave_Index200A,sizeof(TestSlave_Index200A)/sizeof(TestSlave_Index200A[0]), 0x200A},
  { (subindex*)TestSlave_Index200B,sizeof(TestSlave_Index200B)/sizeof(TestSlave_Index200B[0]), 0x200B},
};

const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;*callbacks = TestSlave_Index1003_callbacks; break;
		case 0x1005: i = 3;*callbacks = TestSlave_Index1005_callbacks; break;
		case 0x1006: i = 4;*callbacks = TestSlave_Index1006_callbacks; break;
		case 0x1010: i = 5;*callbacks = TestSlave_Index1010_callbacks; break;
		case 0x1011: i = 6;*callbacks = TestSlave_Index1011_callbacks; break;
		case 0x1014: i = 7;*callbacks = TestSlave_Index1014_callbacks; break;
		case 0x1017: i = 8;*callbacks = TestSlave_Index1017_callbacks; break;
		case 0x1018: i = 9;break;
		case 0x1200: i = 10;break;
		case 0x1400: i = 11;break;
		case 0x1401: i = 12;break;
		case 0x1402: i = 13;break;
		case 0x1403: i = 14;break;
		case 0x1404: i = 15;break;
		case 0x1405: i = 16;break;
		case 0x1406: i = 17;break;
		case 0x1407: i = 18;break;
		case 0x1408: i = 19;break;
		case 0x1409: i = 20;break;
		case 0x140A: i = 21;break;
		case 0x140B: i = 22;break;
		case 0x1600: i = 23;break;
		case 0x1601: i = 24;break;
		case 0x1602: i = 25;break;
		case 0x1603: i = 26;break;
		case 0x1604: i = 27;break;
		case 0x1605: i = 28;break;
		case 0x1606: i = 29;break;
		case 0x1607: i = 30;break;
		case 0x1608: i = 31;break;
		case 0x1609: i = 32;break;
		case 0x160A: i = 33;break;
		case 0x160B: i = 34;break;
		case 0x1800: i = 35;*callbacks = TestSlave_Index1800_callbacks; break;
		case 0x1801: i = 36;*callbacks = TestSlave_Index1801_callbacks; break;
		case 0x1802: i = 37;*callbacks = TestSlave_Index1802_callbacks; break;
		case 0x1803: i = 38;*callbacks = TestSlave_Index1803_callbacks; break;
		case 0x1804: i = 39;*callbacks = TestSlave_Index1804_callbacks; break;
		case 0x1805: i = 40;*callbacks = TestSlave_Index1805_callbacks; break;
		case 0x1806: i = 41;*callbacks = TestSlave_Index1806_callbacks; break;
		case 0x1807: i = 42;*callbacks = TestSlave_Index1807_callbacks; break;
		case 0x1808: i = 43;*callbacks = TestSlave_Index1808_callbacks; break;
		case 0x1809: i = 44;*callbacks = TestSlave_Index1809_callbacks; break;
		case 0x180A: i = 45;*callbacks = TestSlave_Index180A_callbacks; break;
		case 0x180B: i = 46;*callbacks = TestSlave_Index180B_callbacks; break;
		case 0x1A00: i = 47;break;
		case 0x1A01: i = 48;break;
		case 0x1A02: i = 49;*callbacks = TestSlave_Index1A02_callbacks; break;
		case 0x1A03: i = 50;*callbacks = TestSlave_Index1A03_callbacks; break;
		case 0x1A04: i = 51;*callbacks = TestSlave_Index1A04_callbacks; break;
		case 0x1A05: i = 52;*callbacks = TestSlave_Index1A05_callbacks; break;
		case 0x1A06: i = 53;break;
		case 0x1A07: i = 54;break;
		case 0x1A08: i = 55;break;
		case 0x1A09: i = 56;break;
		case 0x1A0A: i = 57;break;
		case 0x1A0B: i = 58;break;
		case 0x2000: i = 59;*callbacks = door_mc1_1_callbacks; break;
		case 0x2001: i = 60;*callbacks = door_mc1_2_callbacks; break;
		case 0x2002: i = 61;*callbacks = door_T_1_callbacks; break;
		case 0x2003: i = 62;*callbacks = door_T_2_callbacks; break;
		case 0x2004: i = 63;*callbacks = door_M_1_callbacks; break;
		case 0x2005: i = 64;*callbacks = door_M_2_callbacks; break;
		case 0x2006: i = 65;*callbacks = door_T1_1_callbacks; break;
		case 0x2007: i = 66;*callbacks = door_T1_2_callbacks; break;
		case 0x2008: i = 67;*callbacks = door_T2_1_callbacks; break;
		case 0x2009: i = 68;*callbacks = door_T2_2_callbacks; break;
		case 0x200A: i = 69;*callbacks = door_mc2_1_callbacks; break;
		case 0x200B: i = 70;*callbacks = door_mc2_2_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestSlave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestSlave_PDO_status[12] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TestSlave_firstIndex = {
  10, /* SDO_SVR */
  0, /* SDO_CLT */
  11, /* PDO_RCV */
  23, /* PDO_RCV_MAP */
  35, /* PDO_TRS */
  47 /* PDO_TRS_MAP */
};

const quick_index TestSlave_lastIndex = {
  10, /* SDO_SVR */
  0, /* SDO_CLT */
  22, /* PDO_RCV */
  34, /* PDO_RCV_MAP */
  46, /* PDO_TRS */
  58 /* PDO_TRS_MAP */
};

const UNS16 TestSlave_ObjdictSize = sizeof(TestSlave_objdict)/sizeof(TestSlave_objdict[0]); 

CO_Data TestSlave_Data = CANOPEN_NODE_DATA_INITIALIZER(TestSlave);

