
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data;
extern UNS64 door_mc1_1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS64 door_mc1_2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS64 door_T_1;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS64 door_T_2;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS64 door_M_1;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS64 door_M_2;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS64 door_T1_1;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS64 door_T1_2;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS64 door_T2_1;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS64 door_T2_2;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS64 door_mc2_1;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS64 door_mc2_2;		/* Mapped at index 0x200B, subindex 0x00*/

#endif // TESTSLAVE_H
