
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CCUCAN1MASTER_H
#define CCUCAN1MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CCUCAN1Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CCUCAN1Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CCUCAN1Master_Data;
extern UNS8 can1_HMITxDev_Time[7];		/* Mapped at index 0x2008, subindex 0x01 - 0x07 */
extern UNS8 can1_MC1SubDevFault[2];		/* Mapped at index 0x2057, subindex 0x01 - 0x02 */
extern UNS8 can1_TSubDevFault[2];		/* Mapped at index 0x2058, subindex 0x01 - 0x02 */
extern UNS8 can1_MSubDevFault[2];		/* Mapped at index 0x2059, subindex 0x01 - 0x02 */
extern UNS8 can1_T1SubDevFault[2];		/* Mapped at index 0x205A, subindex 0x01 - 0x02 */
extern UNS8 can1_T2SubDevFault[2];		/* Mapped at index 0x205B, subindex 0x01 - 0x02 */
extern UNS8 can1_MC2SubDevFault[2];		/* Mapped at index 0x205C, subindex 0x01 - 0x02 */
extern UNS8 can1_CCUTxStatu_SubStatu1;		/* Mapped at index 0x205D, subindex 0x01 */
extern UNS8 can1_CCUTxStatu_SubStatu2;		/* Mapped at index 0x205D, subindex 0x02 */
extern UNS8 can1_CCUTxStatu_CCU1MSStatu;		/* Mapped at index 0x205D, subindex 0x03 */
extern UNS8 can1_CCUTxStatu_CCU2MSStatu;		/* Mapped at index 0x205D, subindex 0x04 */
extern UNS8 can1_CCUTxStatu_CANLineWork;		/* Mapped at index 0x205D, subindex 0x05 */
extern UNS8 can1_CCU1TxLocalMS[1];		/* Mapped at index 0x2076, subindex 0x01 - 0x01 */
extern UNS8 can1_CCU2TxLocalMS[1];		/* Mapped at index 0x2077, subindex 0x01 - 0x01 */
extern UNS8 Can1_CCUNetworkSta;		/* Mapped at index 0x5FFE, subindex 0x00*/

#endif // CCUCAN1MASTER_H
