#ifndef __MTD_CCU_CANADDRES_H__
#define __MTD_CCU_CANADDRES_H__

#include "stm32f4xx.h"
/*定义输入GPIO端口*/
#define  MTDCCU_CANADD0_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD0_GPIO 			 GPIOF
#define  MTDCCU_CANADD0_GPIO_PIN 	 GPIO_Pin_0
#define  MTDCCU_CANADD0_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD0_GPIO,MTDCCU_CANADD0_GPIO_PIN)

#define  MTDCCU_CANADD1_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD1_GPIO 			 GPIOF
#define  MTDCCU_CANADD1_GPIO_PIN 	 GPIO_Pin_1
#define  MTDCCU_CANADD1_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD1_GPIO,MTDCCU_CANADD1_GPIO_PIN)

#define  MTDCCU_CANADD2_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD2_GPIO 			 GPIOF
#define  MTDCCU_CANADD2_GPIO_PIN 	 GPIO_Pin_2
#define  MTDCCU_CANADD2_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD2_GPIO,MTDCCU_CANADD2_GPIO_PIN)

#define  MTDCCU_CANADD3_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD3_GPIO 			 GPIOF
#define  MTDCCU_CANADD3_GPIO_PIN 	 GPIO_Pin_3
#define  MTDCCU_CANADD3_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD3_GPIO,MTDCCU_CANADD3_GPIO_PIN)

#define  MTDCCU_CANADD4_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD4_GPIO 			 GPIOF
#define  MTDCCU_CANADD4_GPIO_PIN 	 GPIO_Pin_4
#define  MTDCCU_CANADD4_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD4_GPIO,MTDCCU_CANADD4_GPIO_PIN)

#define  MTDCCU_CANADD5_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD5_GPIO 			 GPIOF
#define  MTDCCU_CANADD5_GPIO_PIN 	 GPIO_Pin_5
#define  MTDCCU_CANADD5_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD5_GPIO,MTDCCU_CANADD5_GPIO_PIN)

#define  MTDCCU_CANADD6_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD6_GPIO 			 GPIOF
#define  MTDCCU_CANADD6_GPIO_PIN 	 GPIO_Pin_12
#define  MTDCCU_CANADD6_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD6_GPIO,MTDCCU_CANADD6_GPIO_PIN)

#define  MTDCCU_CANADD7_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCCU_CANADD7_GPIO 			 GPIOF
#define  MTDCCU_CANADD7_GPIO_PIN 	 GPIO_Pin_13
#define  MTDCCU_CANADD7_READ()		 GPIO_ReadInputDataBit(MTDCCU_CANADD7_GPIO,MTDCCU_CANADD7_GPIO_PIN)

void MTDCCU_CanAdd_Gpio_Init(void);
uint8_t MTDCCU_CanAddVal(void);

#endif //__MTD_CCU_CANADDRES_H__
