
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CCUCAN1MASTER_H
#define CCUCAN1MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CCUCAN1Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CCUCAN1Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CCUCAN1Master_Data;
extern UNS8 can1_DI_MC1[6];		/* Mapped at index 0x2000, subindex 0x01 - 0x06 */
extern UNS8 can1_DI_T;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 can1_DI_M;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 can1_DI_T1;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 can1_DI_T2;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS8 can1_DI_MC2[6];		/* Mapped at index 0x2005, subindex 0x01 - 0x06 */
extern UNS8 can1_HMITxProData[6];		/* Mapped at index 0x2006, subindex 0x01 - 0x06 */
extern UNS8 can1_MDUTxATO_Time[7];		/* Mapped at index 0x2007, subindex 0x01 - 0x07 */
extern UNS8 can1_HMITxDev_Time[7];		/* Mapped at index 0x2008, subindex 0x01 - 0x07 */
extern UNS8 can1_Door_MC1[3];		/* Mapped at index 0x2009, subindex 0x01 - 0x03 */
extern UNS8 can1_Door_T[3];		/* Mapped at index 0x200A, subindex 0x01 - 0x03 */
extern UNS8 can1_Door_M[3];		/* Mapped at index 0x200B, subindex 0x01 - 0x03 */
extern UNS8 can1_Door_T1[3];		/* Mapped at index 0x200C, subindex 0x01 - 0x03 */
extern UNS8 can1_Door_T2[3];		/* Mapped at index 0x200D, subindex 0x01 - 0x03 */
extern UNS8 can1_Door_MC2[3];		/* Mapped at index 0x200E, subindex 0x01 - 0x03 */
extern UNS8 can1_ACC_MC1[8];		/* Mapped at index 0x200F, subindex 0x01 - 0x08 */
extern UNS8 can1_ACC_T[8];		/* Mapped at index 0x2010, subindex 0x01 - 0x08 */
extern UNS8 can1_ACC_M[8];		/* Mapped at index 0x2011, subindex 0x01 - 0x08 */
extern UNS8 can1_ACC_T1[8];		/* Mapped at index 0x2012, subindex 0x01 - 0x08 */
extern UNS8 can1_ACC_T2[8];		/* Mapped at index 0x2013, subindex 0x01 - 0x08 */
extern UNS8 can1_ACC_MC2[8];		/* Mapped at index 0x2014, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_MC1_1[8];		/* Mapped at index 0x2015, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_MC1_2[8];		/* Mapped at index 0x2016, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_MC1_3[8];		/* Mapped at index 0x2017, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T_1[8];		/* Mapped at index 0x2018, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T_2[8];		/* Mapped at index 0x2019, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T_3[8];		/* Mapped at index 0x201A, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_M_1[8];		/* Mapped at index 0x201B, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_M_2[8];		/* Mapped at index 0x201C, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_M_3[8];		/* Mapped at index 0x201D, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T1_1[8];		/* Mapped at index 0x201E, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T1_2[8];		/* Mapped at index 0x201F, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T1_3[8];		/* Mapped at index 0x2020, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T2_1[8];		/* Mapped at index 0x2021, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T2_2[8];		/* Mapped at index 0x2022, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_T2_3[8];		/* Mapped at index 0x2023, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_MC2_1[8];		/* Mapped at index 0x2024, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_MC2_2[8];		/* Mapped at index 0x2025, subindex 0x01 - 0x08 */
extern UNS8 can1_BCU_MC2_3[8];		/* Mapped at index 0x2026, subindex 0x01 - 0x08 */
extern UNS8 can1_ATC_MC1_1[7];		/* Mapped at index 0x2027, subindex 0x01 - 0x07 */
extern UNS8 can1_ATC_MC1_2[8];		/* Mapped at index 0x2028, subindex 0x01 - 0x08 */
extern UNS8 can1_ATC_MC1_3[8];		/* Mapped at index 0x2029, subindex 0x01 - 0x08 */
extern UNS8 can1_ATC_MC1_4[4];		/* Mapped at index 0x202A, subindex 0x01 - 0x04 */
extern UNS8 can1_ATC_MC2_1[7];		/* Mapped at index 0x202B, subindex 0x01 - 0x07 */
extern UNS8 can1_ATC_MC2_2[8];		/* Mapped at index 0x202C, subindex 0x01 - 0x08 */
extern UNS8 can1_ATC_MC2_3[8];		/* Mapped at index 0x202D, subindex 0x01 - 0x08 */
extern UNS8 can1_ATC_MC2_4[4];		/* Mapped at index 0x202E, subindex 0x01 - 0x04 */
extern UNS8 can1_PIS_MC1_1[8];		/* Mapped at index 0x202F, subindex 0x01 - 0x08 */
extern UNS8 can1_PIS_MC1_2[3];		/* Mapped at index 0x2030, subindex 0x01 - 0x03 */
extern UNS8 can1_PIS_MC2_1[8];		/* Mapped at index 0x2031, subindex 0x01 - 0x08 */
extern UNS8 can1_PIS_MC2_2[3];		/* Mapped at index 0x2032, subindex 0x01 - 0x03 */
extern UNS8 can1_VVVF1_MC1_1[8];		/* Mapped at index 0x2033, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_MC1_2[6];		/* Mapped at index 0x2034, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF1_MC1_3[8];		/* Mapped at index 0x2035, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_MC1_4[8];		/* Mapped at index 0x2036, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_MC1_5[6];		/* Mapped at index 0x2037, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF2_MC1_1[8];		/* Mapped at index 0x2038, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_MC1_2[6];		/* Mapped at index 0x2039, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF2_MC1_3[8];		/* Mapped at index 0x203A, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_MC1_4[8];		/* Mapped at index 0x203B, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_MC1_5[6];		/* Mapped at index 0x203C, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF1_M_1[8];		/* Mapped at index 0x203D, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_M_2[6];		/* Mapped at index 0x203E, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF1_M_3[8];		/* Mapped at index 0x203F, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_M_4[8];		/* Mapped at index 0x2040, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_M_5[6];		/* Mapped at index 0x2041, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF2_M_1[8];		/* Mapped at index 0x2042, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_M_2[6];		/* Mapped at index 0x2043, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF2_M_3[8];		/* Mapped at index 0x2044, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_M_4[8];		/* Mapped at index 0x2045, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_M_5[6];		/* Mapped at index 0x2046, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF1_MC2_1[8];		/* Mapped at index 0x2047, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_MC2_2[6];		/* Mapped at index 0x2048, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF1_MC2_3[8];		/* Mapped at index 0x2049, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_MC2_4[8];		/* Mapped at index 0x204A, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF1_MC2_5[6];		/* Mapped at index 0x204B, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF2_MC2_1[8];		/* Mapped at index 0x204C, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_MC2_2[6];		/* Mapped at index 0x204D, subindex 0x01 - 0x06 */
extern UNS8 can1_VVVF2_MC2_3[8];		/* Mapped at index 0x204E, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_MC2_4[8];		/* Mapped at index 0x204F, subindex 0x01 - 0x08 */
extern UNS8 can1_VVVF2_MC2_5[6];		/* Mapped at index 0x2050, subindex 0x01 - 0x06 */
extern UNS8 can1_SIV_T_1[6];		/* Mapped at index 0x2051, subindex 0x01 - 0x06 */
extern UNS8 can1_SIV_T_2[8];		/* Mapped at index 0x2052, subindex 0x01 - 0x08 */
extern UNS8 can1_SIV_T_3[3];		/* Mapped at index 0x2053, subindex 0x01 - 0x03 */
extern UNS8 can1_SIV_T1_1[6];		/* Mapped at index 0x2054, subindex 0x01 - 0x06 */
extern UNS8 can1_SIV_T1_2[8];		/* Mapped at index 0x2055, subindex 0x01 - 0x08 */
extern UNS8 can1_SIV_T1_3[3];		/* Mapped at index 0x2056, subindex 0x01 - 0x03 */
extern UNS8 can1_MC1SubDevFault_ATC_MC1;		/* Mapped at index 0x2057, subindex 0x01 */
extern UNS8 can1_MC1SubDevFault_ACP_MC1;		/* Mapped at index 0x2057, subindex 0x02 */
extern UNS8 can1_MC1SubDevFault_PIS_MC1;		/* Mapped at index 0x2057, subindex 0x03 */
extern UNS8 can1_MC1SubDevFault_VVVF2_MC1;		/* Mapped at index 0x2057, subindex 0x04 */
extern UNS8 can1_MC1SubDevFault_VVVF1_MC1;		/* Mapped at index 0x2057, subindex 0x05 */
extern UNS8 can1_MC1SubDevFault_BCU_MC1;		/* Mapped at index 0x2057, subindex 0x06 */
extern UNS8 can1_MC1SubDevFault_ACC_MC1;		/* Mapped at index 0x2057, subindex 0x07 */
extern UNS8 can1_MC1SubDevFault_Door_MC1;		/* Mapped at index 0x2057, subindex 0x08 */
extern UNS8 can1_TSubDevFault_Undefined1;		/* Mapped at index 0x2058, subindex 0x01 */
extern UNS8 can1_TSubDevFault_Undefined2;		/* Mapped at index 0x2058, subindex 0x02 */
extern UNS8 can1_TSubDevFault_Undefined3;		/* Mapped at index 0x2058, subindex 0x03 */
extern UNS8 can1_TSubDevFault_Undefined4;		/* Mapped at index 0x2058, subindex 0x04 */
extern UNS8 can1_TSubDevFault_SIV_T;		/* Mapped at index 0x2058, subindex 0x05 */
extern UNS8 can1_TSubDevFault_BCU_T;		/* Mapped at index 0x2058, subindex 0x06 */
extern UNS8 can1_TSubDevFault_ACC_T;		/* Mapped at index 0x2058, subindex 0x07 */
extern UNS8 can1_TSubDevFault_Door_T;		/* Mapped at index 0x2058, subindex 0x08 */
extern UNS8 can1_MSubDevFault_Undefined1;		/* Mapped at index 0x2059, subindex 0x01 */
extern UNS8 can1_MSubDevFault_Undefined2;		/* Mapped at index 0x2059, subindex 0x02 */
extern UNS8 can1_MSubDevFault_Undefined3;		/* Mapped at index 0x2059, subindex 0x03 */
extern UNS8 can1_MSubDevFault_VVVF2_M;		/* Mapped at index 0x2059, subindex 0x04 */
extern UNS8 can1_MSubDevFault_VVVF1_M;		/* Mapped at index 0x2059, subindex 0x05 */
extern UNS8 can1_MSubDevFault_BCU_M;		/* Mapped at index 0x2059, subindex 0x06 */
extern UNS8 can1_MSubDevFault_ACC_M;		/* Mapped at index 0x2059, subindex 0x07 */
extern UNS8 can1_MSubDevFault_Door_M;		/* Mapped at index 0x2059, subindex 0x08 */
extern UNS8 can1_T1SubDevFault_Undefined1;		/* Mapped at index 0x205A, subindex 0x01 */
extern UNS8 can1_T1SubDevFault_Undefined2;		/* Mapped at index 0x205A, subindex 0x02 */
extern UNS8 can1_T1SubDevFault_Undefined3;		/* Mapped at index 0x205A, subindex 0x03 */
extern UNS8 can1_T1SubDevFault_Undefined4;		/* Mapped at index 0x205A, subindex 0x04 */
extern UNS8 can1_T1SubDevFault_SIV_T1;		/* Mapped at index 0x205A, subindex 0x05 */
extern UNS8 can1_T1SubDevFault_BCU_T1;		/* Mapped at index 0x205A, subindex 0x06 */
extern UNS8 can1_T1SubDevFault_ACC_T1;		/* Mapped at index 0x205A, subindex 0x07 */
extern UNS8 can1_T1SubDevFault_Door_T1;		/* Mapped at index 0x205A, subindex 0x08 */
extern UNS8 can1_T2SubDevFault_Undefined1;		/* Mapped at index 0x205B, subindex 0x01 */
extern UNS8 can1_T2SubDevFault_Undefined2;		/* Mapped at index 0x205B, subindex 0x02 */
extern UNS8 can1_T2SubDevFault_Undefined3;		/* Mapped at index 0x205B, subindex 0x03 */
extern UNS8 can1_T2SubDevFault_Undefined4;		/* Mapped at index 0x205B, subindex 0x04 */
extern UNS8 can1_T2SubDevFault_Undefined5;		/* Mapped at index 0x205B, subindex 0x05 */
extern UNS8 can1_T2SubDevFault_BCU_T2;		/* Mapped at index 0x205B, subindex 0x06 */
extern UNS8 can1_T2SubDevFault_ACC_T2;		/* Mapped at index 0x205B, subindex 0x07 */
extern UNS8 can1_T2SubDevFault_Door_T2;		/* Mapped at index 0x205B, subindex 0x08 */
extern UNS8 can1_MC2SubDevFault_ATC_MC2;		/* Mapped at index 0x205C, subindex 0x01 */
extern UNS8 can1_MC2SubDevFault_ACP_MC2;		/* Mapped at index 0x205C, subindex 0x02 */
extern UNS8 can1_MC2SubDevFault_PIS_MC2;		/* Mapped at index 0x205C, subindex 0x03 */
extern UNS8 can1_MC2SubDevFault_VVVF2_MC2;		/* Mapped at index 0x205C, subindex 0x04 */
extern UNS8 can1_MC2SubDevFault_VVVF1_MC2;		/* Mapped at index 0x205C, subindex 0x05 */
extern UNS8 can1_MC2SubDevFault_BCU_MC2;		/* Mapped at index 0x205C, subindex 0x06 */
extern UNS8 can1_MC2SubDevFault_ACC_MC2;		/* Mapped at index 0x205C, subindex 0x07 */
extern UNS8 can1_MC2SubDevFault_Door_MC2;		/* Mapped at index 0x205C, subindex 0x08 */
extern UNS8 can1_CCUTxStatu_MDU6Fault;		/* Mapped at index 0x205D, subindex 0x01 */
extern UNS8 can1_CCUTxStatu_MDU5Fault;		/* Mapped at index 0x205D, subindex 0x02 */
extern UNS8 can1_CCUTxStatu_MDU4Fault;		/* Mapped at index 0x205D, subindex 0x03 */
extern UNS8 can1_CCUTxStatu_MDU3Fault;		/* Mapped at index 0x205D, subindex 0x04 */
extern UNS8 can1_CCUTxStatu_MDU2Fault;		/* Mapped at index 0x205D, subindex 0x05 */
extern UNS8 can1_CCUTxStatu_MDU1Fault;		/* Mapped at index 0x205D, subindex 0x06 */
extern UNS8 can1_CCUTxStatu_HMI6Fault;		/* Mapped at index 0x205D, subindex 0x07 */
extern UNS8 can1_CCUTxStatu_HMI1Fault;		/* Mapped at index 0x205D, subindex 0x08 */
extern UNS8 can1_CCUTxStatu_Byte2UndefBit0;		/* Mapped at index 0x205D, subindex 0x09 */
extern UNS8 can1_CCUTxStatu_Byte2UndefBit1;		/* Mapped at index 0x205D, subindex 0x0A */
extern UNS8 can1_CCUTxStatu_Byte2UndefBit2;		/* Mapped at index 0x205D, subindex 0x0B */
extern UNS8 can1_CCUTxStatu_Byte2UndefBit3;		/* Mapped at index 0x205D, subindex 0x0C */
extern UNS8 can1_CCUTxStatu_CCU6Fault;		/* Mapped at index 0x205D, subindex 0x0D */
extern UNS8 can1_CCUTxStatu_CCU1Fault;		/* Mapped at index 0x205D, subindex 0x0E */
extern UNS8 can1_CCUTxStatu_ERM6Fault;		/* Mapped at index 0x205D, subindex 0x0F */
extern UNS8 can1_CCUTxStatu_ERM1Fault;		/* Mapped at index 0x205D, subindex 0x10 */
extern UNS8 can1_CCUTxStatu_CCU1MSStatu;		/* Mapped at index 0x205D, subindex 0x11 */
extern UNS8 can1_CCUTxStatu_CCU2MSStatu;		/* Mapped at index 0x205D, subindex 0x12 */
extern UNS8 can1_CCUTxStatu_CANLineWork;		/* Mapped at index 0x205D, subindex 0x13 */
extern UNS8 can1_HMITxWhellAndNo_NoH8;		/* Mapped at index 0x205E, subindex 0x01 */
extern UNS8 can1_HMITxWhellAndNo_NoL8;		/* Mapped at index 0x205E, subindex 0x02 */
extern UNS8 can1_HMITxWhellAndNo_Car1WhellDia;		/* Mapped at index 0x205E, subindex 0x03 */
extern UNS8 can1_HMITxWhellAndNo_Car2WhellDia;		/* Mapped at index 0x205E, subindex 0x04 */
extern UNS8 can1_HMITxWhellAndNo_Car3WhellDia;		/* Mapped at index 0x205E, subindex 0x05 */
extern UNS8 can1_HMITxWhellAndNo_Car4WhellDia;		/* Mapped at index 0x205E, subindex 0x06 */
extern UNS8 can1_HMITxWhellAndNo_Car5WhellDia;		/* Mapped at index 0x205E, subindex 0x07 */
extern UNS8 can1_HMITxWhellAndNo_Car6WhellDia;		/* Mapped at index 0x205E, subindex 0x08 */
extern UNS8 can1_HMITx1And2AS[8];		/* Mapped at index 0x205F, subindex 0x01 - 0x08 */
extern UNS8 can1_HMITx3And4AS[8];		/* Mapped at index 0x2060, subindex 0x01 - 0x08 */
extern UNS8 can1_HMITx5And6AS[8];		/* Mapped at index 0x2061, subindex 0x01 - 0x08 */
extern UNS8 can1_HMITxAccTemp[2];		/* Mapped at index 0x2062, subindex 0x01 - 0x02 */
extern UNS8 can1_ACC_MC1_2;		/* Mapped at index 0x2063, subindex 0x00*/
extern UNS8 can1_ACC_T_2;		/* Mapped at index 0x2064, subindex 0x00*/
extern UNS8 can1_ACC_M_2;		/* Mapped at index 0x2065, subindex 0x00*/
extern UNS8 can1_ACC_T1_2;		/* Mapped at index 0x2066, subindex 0x00*/
extern UNS8 can1_ACC_T2_2;		/* Mapped at index 0x2067, subindex 0x00*/
extern UNS8 can1_ACC_MC2_2;		/* Mapped at index 0x2068, subindex 0x00*/
extern UNS8 can1_HMITxStaReqCmd[2];		/* Mapped at index 0x2069, subindex 0x01 - 0x02 */
extern UNS8 can1_HMITxDelRecordCmd[3];		/* Mapped at index 0x206A, subindex 0x01 - 0x03 */
extern UNS8 can1_HMITxInitData[8];		/* Mapped at index 0x206B, subindex 0x01 - 0x08 */

#endif // CCUCAN1MASTER_H
