
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CCUCAN2MASTER_H
#define CCUCAN2MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CCUCAN2Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CCUCAN2Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CCUCAN2Master_Data;
extern UNS8 can2_HMITxDev_Time[7];		/* Mapped at index 0x2008, subindex 0x01 - 0x07 */
extern UNS8 can2_MC1SubDevFault[2];		/* Mapped at index 0x2057, subindex 0x01 - 0x02 */
extern UNS8 can2_TSubDevFault[2];		/* Mapped at index 0x2058, subindex 0x01 - 0x02 */
extern UNS8 can2_MSubDevFault[2];		/* Mapped at index 0x2059, subindex 0x01 - 0x02 */
extern UNS8 can2_T1SubDevFault[2];		/* Mapped at index 0x205A, subindex 0x01 - 0x02 */
extern UNS8 can2_T2SubDevFault[2];		/* Mapped at index 0x205B, subindex 0x01 - 0x02 */
extern UNS8 can2_MC2SubDevFault[2];		/* Mapped at index 0x205C, subindex 0x01 - 0x02 */
extern UNS8 can2_CCUTxStatu_SubStatu1;		/* Mapped at index 0x205D, subindex 0x01 */
extern UNS8 can2_CCUTxStatu_SubStatu2;		/* Mapped at index 0x205D, subindex 0x02 */
extern UNS8 can2_CCUTxStatu_CCU1MSStatu;		/* Mapped at index 0x205D, subindex 0x03 */
extern UNS8 can2_CCUTxStatu_CCU2MSStatu;		/* Mapped at index 0x205D, subindex 0x04 */
extern UNS8 can2_CCUTxStatu_CANLineWork;		/* Mapped at index 0x205D, subindex 0x05 */
extern UNS8 can2_CCU1TxLocalMS[1];		/* Mapped at index 0x2076, subindex 0x01 - 0x01 */
extern UNS8 can2_CCU2TxLocalMS[1];		/* Mapped at index 0x2077, subindex 0x01 - 0x01 */
extern UNS8 Can2_CCUNetworkSta;		/* Mapped at index 0x5FFE, subindex 0x00*/
extern UNS8 IAP_M_IAP_SEG[256];		/* Mapped at index 0x5FFF, subindex 0x01 */
extern UNS64 IAP_M_IAP_CMD;		/* Mapped at index 0x5FFF, subindex 0x02 */
extern UNS64 IAP_M_IAP_CMD_R;		/* Mapped at index 0x5FFF, subindex 0x03 */

#endif // CCUCAN2MASTER_H
