
/* File generated by gen_cfile.py. Should not be modified. */

#include "CCUCAN2Master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 can2_HMITxDev_Time[] =		/* Mapped at index 0x2008, subindex 0x01 - 0x07 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 can2_MC1SubDevFault[] =		/* Mapped at index 0x2057, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 can2_TSubDevFault[] =		/* Mapped at index 0x2058, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 can2_MSubDevFault[] =		/* Mapped at index 0x2059, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 can2_T1SubDevFault[] =		/* Mapped at index 0x205A, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 can2_T2SubDevFault[] =		/* Mapped at index 0x205B, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 can2_MC2SubDevFault[] =		/* Mapped at index 0x205C, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 can2_CCUTxStatu_SubStatu1 = 0x0;		/* Mapped at index 0x205D, subindex 0x01 */
UNS8 can2_CCUTxStatu_SubStatu2 = 0x0;		/* Mapped at index 0x205D, subindex 0x02 */
UNS8 can2_CCUTxStatu_CCU1MSStatu = 0x0;		/* Mapped at index 0x205D, subindex 0x03 */
UNS8 can2_CCUTxStatu_CCU2MSStatu = 0x0;		/* Mapped at index 0x205D, subindex 0x04 */
UNS8 can2_CCUTxStatu_CANLineWork = 0x0;		/* Mapped at index 0x205D, subindex 0x05 */
UNS8 can2_CCU1TxLocalMS[] =		/* Mapped at index 0x2076, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 can2_CCU2TxLocalMS[] =		/* Mapped at index 0x2077, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Can2_CCUNetworkSta = 0x0;		/* Mapped at index 0x5FFE, subindex 0x00 */
UNS8 IAP_M_IAP_SEG[256] = "\x01\x00";		/* Mapped at index 0x5FFF, subindex 0x01 */
UNS64 IAP_M_IAP_CMD = 0x0;		/* Mapped at index 0x5FFF, subindex 0x02 */
UNS64 IAP_M_IAP_CMD_R = 0x0;		/* Mapped at index 0x5FFF, subindex 0x03 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 CCUCAN2Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 CCUCAN2Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 CCUCAN2Master_iam_a_slave = 0;

TIMER_HANDLE CCUCAN2Master_heartBeatTimers[10] = {TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 CCUCAN2Master_obj1000 = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 CCUCAN2Master_obj1001 = 0x2;	/* 2 */
                    subindex CCUCAN2Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t CCUCAN2Master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex CCUCAN2Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 CCUCAN2Master_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 CCUCAN2Master_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 CCUCAN2Master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 CCUCAN2Master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 CCUCAN2Master_obj1014 = 0x80;	/* 128 */
                    subindex CCUCAN2Master_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1014 }
                     };

/* index 0x1015 :   Inhibit Time Emergency. */
                    UNS16 CCUCAN2Master_obj1015 = 0x12C;	/* 300 */
                    subindex CCUCAN2Master_Index1015[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1015 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1016 = 10; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1016[] = 
                    {
                      0x10BB8,	/* 68536 */
                      0x20BB8,	/* 134072 */
                      0x30BB8,	/* 199608 */
                      0x40BB8,	/* 265144 */
                      0x50BB8,	/* 330680 */
                      0x60BB8,	/* 396216 */
                      0x70BB8,	/* 461752 */
                      0x80BB8,	/* 527288 */
                      0x90BB8,	/* 592824 */
                      0xA0BB8	/* 658360 */
                    };
                    subindex CCUCAN2Master_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[7] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[8] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1016[9] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 CCUCAN2Master_obj1017 = 0x190;	/* 400 */
                    ODCallback_t CCUCAN2Master_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CCUCAN2Master_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 CCUCAN2Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 CCUCAN2Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 CCUCAN2Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 CCUCAN2Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex CCUCAN2Master_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 CCUCAN2Master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1400_COB_ID_used_by_PDO = 0x18B;	/* 395 */
                    UNS8 CCUCAN2Master_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1401_COB_ID_used_by_PDO = 0x1DA;	/* 474 */
                    UNS8 CCUCAN2Master_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1402_COB_ID_used_by_PDO = 0x1DB;	/* 475 */
                    UNS8 CCUCAN2Master_obj1402_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1403_COB_ID_used_by_PDO = 0x1DC;	/* 476 */
                    UNS8 CCUCAN2Master_obj1403_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1403_SYNC_start_value }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1404_COB_ID_used_by_PDO = 0x1DD;	/* 477 */
                    UNS8 CCUCAN2Master_obj1404_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1404_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1404_SYNC_start_value }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1405_COB_ID_used_by_PDO = 0x1DE;	/* 478 */
                    UNS8 CCUCAN2Master_obj1405_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1405_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1405_SYNC_start_value }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1406_COB_ID_used_by_PDO = 0x1DF;	/* 479 */
                    UNS8 CCUCAN2Master_obj1406_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1406_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1406_SYNC_start_value }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1407_COB_ID_used_by_PDO = 0x1E0;	/* 480 */
                    UNS8 CCUCAN2Master_obj1407_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1407_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1407_SYNC_start_value }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1408 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1408_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 CCUCAN2Master_obj1408_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1408_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1408_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1408_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1408_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1408_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1408_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1408_SYNC_start_value }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1409 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1409_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 CCUCAN2Master_obj1409_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1409_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1409_SYNC_start_value = 0x0;	/* 0 */
                    subindex CCUCAN2Master_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1409_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1409_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1409_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1409_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1409_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1600 = 7; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1600[] = 
                    {
                      0x20080108,	/* 537395464 */
                      0x20080208,	/* 537395720 */
                      0x20080308,	/* 537395976 */
                      0x20080408,	/* 537396232 */
                      0x20080508,	/* 537396488 */
                      0x20080608,	/* 537396744 */
                      0x20080708	/* 537397000 */
                    };
                    subindex CCUCAN2Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1600[6] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1601[] = 
                    {
                      0x20570108,	/* 542572808 */
                      0x20570208	/* 542573064 */
                    };
                    subindex CCUCAN2Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1601[1] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1602[] = 
                    {
                      0x20580108,	/* 542638344 */
                      0x20580208	/* 542638600 */
                    };
                    subindex CCUCAN2Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1602[1] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1603 = 2; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1603[] = 
                    {
                      0x20590108,	/* 542703880 */
                      0x20590208	/* 542704136 */
                    };
                    subindex CCUCAN2Master_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1603[1] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1604 = 2; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1604[] = 
                    {
                      0x205A0108,	/* 542769416 */
                      0x205A0208	/* 542769672 */
                    };
                    subindex CCUCAN2Master_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1604[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1604[1] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1605 = 2; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1605[] = 
                    {
                      0x205B0108,	/* 542834952 */
                      0x205B0208	/* 542835208 */
                    };
                    subindex CCUCAN2Master_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1605[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1605[1] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1606 = 2; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1606[] = 
                    {
                      0x205C0108,	/* 542900488 */
                      0x205C0208	/* 542900744 */
                    };
                    subindex CCUCAN2Master_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1606[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1606[1] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1607 = 5; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1607[] = 
                    {
                      0x205D0108,	/* 542966024 */
                      0x205D0208,	/* 542966280 */
                      0x205D0308,	/* 542966536 */
                      0x205D0408,	/* 542966792 */
                      0x205D0508	/* 542967048 */
                    };
                    subindex CCUCAN2Master_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1607[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1607[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1607[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1607[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1607[4] }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1608 = 1; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1608[] = 
                    {
                      0x20760108	/* 544604424 */
                    };
                    subindex CCUCAN2Master_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1608 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1608[0] }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1609 = 1; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1609[] = 
                    {
                      0x20770108	/* 544669960 */
                    };
                    subindex CCUCAN2Master_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1609 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1609[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1800_COB_ID_used_by_PDO = 0x1E0;	/* 480 */
                    UNS8 CCUCAN2Master_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 CCUCAN2Master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CCUCAN2Master_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 CCUCAN2Master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t CCUCAN2Master_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CCUCAN2Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CCUCAN2Master_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_obj1800_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 CCUCAN2Master_highestSubIndex_obj1A00 = 5; /* number of subindex - 1*/
                    UNS32 CCUCAN2Master_obj1A00[] = 
                    {
                      0x205D0108,	/* 542966024 */
                      0x205D0208,	/* 542966280 */
                      0x205D0308,	/* 542966536 */
                      0x205D0408,	/* 542966792 */
                      0x205D0508	/* 542967048 */
                    };
                    subindex CCUCAN2Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&CCUCAN2Master_obj1A00[4] }
                     };

/* index 0x2008 :   Mapped variable can2_HMITxDev_Time */
                    UNS8 CCUCAN2Master_highestSubIndex_obj2008 = 7; /* number of subindex - 1*/
                    ODCallback_t can2_HMITxDev_Time_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CCUCAN2Master_Index2008[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj2008 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_HMITxDev_Time[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_HMITxDev_Time[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_HMITxDev_Time[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_HMITxDev_Time[3] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_HMITxDev_Time[4] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_HMITxDev_Time[5] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_HMITxDev_Time[6] }
                     };

/* index 0x2057 :   Mapped variable can2_MC1SubDevFault */
                    UNS8 CCUCAN2Master_highestSubIndex_obj2057 = 2; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index2057[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj2057 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_MC1SubDevFault[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_MC1SubDevFault[1] }
                     };

/* index 0x2058 :   Mapped variable can2_TSubDevFault */
                    UNS8 CCUCAN2Master_highestSubIndex_obj2058 = 2; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index2058[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj2058 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_TSubDevFault[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_TSubDevFault[1] }
                     };

/* index 0x2059 :   Mapped variable can2_MSubDevFault */
                    UNS8 CCUCAN2Master_highestSubIndex_obj2059 = 2; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index2059[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj2059 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_MSubDevFault[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_MSubDevFault[1] }
                     };

/* index 0x205A :   Mapped variable can2_T1SubDevFault */
                    UNS8 CCUCAN2Master_highestSubIndex_obj205A = 2; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index205A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj205A },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_T1SubDevFault[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_T1SubDevFault[1] }
                     };

/* index 0x205B :   Mapped variable can2_T2SubDevFault */
                    UNS8 CCUCAN2Master_highestSubIndex_obj205B = 2; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index205B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj205B },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_T2SubDevFault[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_T2SubDevFault[1] }
                     };

/* index 0x205C :   Mapped variable can2_MC2SubDevFault */
                    UNS8 CCUCAN2Master_highestSubIndex_obj205C = 2; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index205C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj205C },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_MC2SubDevFault[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_MC2SubDevFault[1] }
                     };

/* index 0x205D :   Mapped variable can2_CCUTxStatu */
                    UNS8 CCUCAN2Master_highestSubIndex_obj205D = 5; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index205D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj205D },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_CCUTxStatu_SubStatu1 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_CCUTxStatu_SubStatu2 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_CCUTxStatu_CCU1MSStatu },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_CCUTxStatu_CCU2MSStatu },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_CCUTxStatu_CANLineWork }
                     };

/* index 0x2076 :   Mapped variable can2_CCU1TxLocalMS */
                    UNS8 CCUCAN2Master_highestSubIndex_obj2076 = 1; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index2076[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj2076 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_CCU1TxLocalMS[0] }
                     };

/* index 0x2077 :   Mapped variable can2_CCU2TxLocalMS */
                    UNS8 CCUCAN2Master_highestSubIndex_obj2077 = 1; /* number of subindex - 1*/
                    subindex CCUCAN2Master_Index2077[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj2077 },
                       { RW, uint8, sizeof (UNS8), (void*)&can2_CCU2TxLocalMS[0] }
                     };

/* index 0x5FFE :   Mapped variable Can2_CCUNetworkSta */
                    subindex CCUCAN2Master_Index5FFE[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Can2_CCUNetworkSta }
                     };

/* index 0x5FFF :   Mapped variable IAP_M */
                    UNS8 CCUCAN2Master_highestSubIndex_obj5FFF = 3; /* number of subindex - 1*/
                    ODCallback_t IAP_M_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CCUCAN2Master_Index5FFF[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CCUCAN2Master_highestSubIndex_obj5FFF },
                       { RW, domain, 256, (void*)&IAP_M_IAP_SEG },
                       { RW, uint64, sizeof (UNS64), (void*)&IAP_M_IAP_CMD },
                       { RW, uint64, sizeof (UNS64), (void*)&IAP_M_IAP_CMD_R }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable CCUCAN2Master_objdict[] = 
{
  { (subindex*)CCUCAN2Master_Index1000,sizeof(CCUCAN2Master_Index1000)/sizeof(CCUCAN2Master_Index1000[0]), 0x1000},
  { (subindex*)CCUCAN2Master_Index1001,sizeof(CCUCAN2Master_Index1001)/sizeof(CCUCAN2Master_Index1001[0]), 0x1001},
  { (subindex*)CCUCAN2Master_Index1014,sizeof(CCUCAN2Master_Index1014)/sizeof(CCUCAN2Master_Index1014[0]), 0x1014},
  { (subindex*)CCUCAN2Master_Index1015,sizeof(CCUCAN2Master_Index1015)/sizeof(CCUCAN2Master_Index1015[0]), 0x1015},
  { (subindex*)CCUCAN2Master_Index1016,sizeof(CCUCAN2Master_Index1016)/sizeof(CCUCAN2Master_Index1016[0]), 0x1016},
  { (subindex*)CCUCAN2Master_Index1017,sizeof(CCUCAN2Master_Index1017)/sizeof(CCUCAN2Master_Index1017[0]), 0x1017},
  { (subindex*)CCUCAN2Master_Index1018,sizeof(CCUCAN2Master_Index1018)/sizeof(CCUCAN2Master_Index1018[0]), 0x1018},
  { (subindex*)CCUCAN2Master_Index1200,sizeof(CCUCAN2Master_Index1200)/sizeof(CCUCAN2Master_Index1200[0]), 0x1200},
  { (subindex*)CCUCAN2Master_Index1280,sizeof(CCUCAN2Master_Index1280)/sizeof(CCUCAN2Master_Index1280[0]), 0x1280},
  { (subindex*)CCUCAN2Master_Index1400,sizeof(CCUCAN2Master_Index1400)/sizeof(CCUCAN2Master_Index1400[0]), 0x1400},
  { (subindex*)CCUCAN2Master_Index1401,sizeof(CCUCAN2Master_Index1401)/sizeof(CCUCAN2Master_Index1401[0]), 0x1401},
  { (subindex*)CCUCAN2Master_Index1402,sizeof(CCUCAN2Master_Index1402)/sizeof(CCUCAN2Master_Index1402[0]), 0x1402},
  { (subindex*)CCUCAN2Master_Index1403,sizeof(CCUCAN2Master_Index1403)/sizeof(CCUCAN2Master_Index1403[0]), 0x1403},
  { (subindex*)CCUCAN2Master_Index1404,sizeof(CCUCAN2Master_Index1404)/sizeof(CCUCAN2Master_Index1404[0]), 0x1404},
  { (subindex*)CCUCAN2Master_Index1405,sizeof(CCUCAN2Master_Index1405)/sizeof(CCUCAN2Master_Index1405[0]), 0x1405},
  { (subindex*)CCUCAN2Master_Index1406,sizeof(CCUCAN2Master_Index1406)/sizeof(CCUCAN2Master_Index1406[0]), 0x1406},
  { (subindex*)CCUCAN2Master_Index1407,sizeof(CCUCAN2Master_Index1407)/sizeof(CCUCAN2Master_Index1407[0]), 0x1407},
  { (subindex*)CCUCAN2Master_Index1408,sizeof(CCUCAN2Master_Index1408)/sizeof(CCUCAN2Master_Index1408[0]), 0x1408},
  { (subindex*)CCUCAN2Master_Index1409,sizeof(CCUCAN2Master_Index1409)/sizeof(CCUCAN2Master_Index1409[0]), 0x1409},
  { (subindex*)CCUCAN2Master_Index1600,sizeof(CCUCAN2Master_Index1600)/sizeof(CCUCAN2Master_Index1600[0]), 0x1600},
  { (subindex*)CCUCAN2Master_Index1601,sizeof(CCUCAN2Master_Index1601)/sizeof(CCUCAN2Master_Index1601[0]), 0x1601},
  { (subindex*)CCUCAN2Master_Index1602,sizeof(CCUCAN2Master_Index1602)/sizeof(CCUCAN2Master_Index1602[0]), 0x1602},
  { (subindex*)CCUCAN2Master_Index1603,sizeof(CCUCAN2Master_Index1603)/sizeof(CCUCAN2Master_Index1603[0]), 0x1603},
  { (subindex*)CCUCAN2Master_Index1604,sizeof(CCUCAN2Master_Index1604)/sizeof(CCUCAN2Master_Index1604[0]), 0x1604},
  { (subindex*)CCUCAN2Master_Index1605,sizeof(CCUCAN2Master_Index1605)/sizeof(CCUCAN2Master_Index1605[0]), 0x1605},
  { (subindex*)CCUCAN2Master_Index1606,sizeof(CCUCAN2Master_Index1606)/sizeof(CCUCAN2Master_Index1606[0]), 0x1606},
  { (subindex*)CCUCAN2Master_Index1607,sizeof(CCUCAN2Master_Index1607)/sizeof(CCUCAN2Master_Index1607[0]), 0x1607},
  { (subindex*)CCUCAN2Master_Index1608,sizeof(CCUCAN2Master_Index1608)/sizeof(CCUCAN2Master_Index1608[0]), 0x1608},
  { (subindex*)CCUCAN2Master_Index1609,sizeof(CCUCAN2Master_Index1609)/sizeof(CCUCAN2Master_Index1609[0]), 0x1609},
  { (subindex*)CCUCAN2Master_Index1800,sizeof(CCUCAN2Master_Index1800)/sizeof(CCUCAN2Master_Index1800[0]), 0x1800},
  { (subindex*)CCUCAN2Master_Index1A00,sizeof(CCUCAN2Master_Index1A00)/sizeof(CCUCAN2Master_Index1A00[0]), 0x1A00},
  { (subindex*)CCUCAN2Master_Index2008,sizeof(CCUCAN2Master_Index2008)/sizeof(CCUCAN2Master_Index2008[0]), 0x2008},
  { (subindex*)CCUCAN2Master_Index2057,sizeof(CCUCAN2Master_Index2057)/sizeof(CCUCAN2Master_Index2057[0]), 0x2057},
  { (subindex*)CCUCAN2Master_Index2058,sizeof(CCUCAN2Master_Index2058)/sizeof(CCUCAN2Master_Index2058[0]), 0x2058},
  { (subindex*)CCUCAN2Master_Index2059,sizeof(CCUCAN2Master_Index2059)/sizeof(CCUCAN2Master_Index2059[0]), 0x2059},
  { (subindex*)CCUCAN2Master_Index205A,sizeof(CCUCAN2Master_Index205A)/sizeof(CCUCAN2Master_Index205A[0]), 0x205A},
  { (subindex*)CCUCAN2Master_Index205B,sizeof(CCUCAN2Master_Index205B)/sizeof(CCUCAN2Master_Index205B[0]), 0x205B},
  { (subindex*)CCUCAN2Master_Index205C,sizeof(CCUCAN2Master_Index205C)/sizeof(CCUCAN2Master_Index205C[0]), 0x205C},
  { (subindex*)CCUCAN2Master_Index205D,sizeof(CCUCAN2Master_Index205D)/sizeof(CCUCAN2Master_Index205D[0]), 0x205D},
  { (subindex*)CCUCAN2Master_Index2076,sizeof(CCUCAN2Master_Index2076)/sizeof(CCUCAN2Master_Index2076[0]), 0x2076},
  { (subindex*)CCUCAN2Master_Index2077,sizeof(CCUCAN2Master_Index2077)/sizeof(CCUCAN2Master_Index2077[0]), 0x2077},
  { (subindex*)CCUCAN2Master_Index5FFE,sizeof(CCUCAN2Master_Index5FFE)/sizeof(CCUCAN2Master_Index5FFE[0]), 0x5FFE},
  { (subindex*)CCUCAN2Master_Index5FFF,sizeof(CCUCAN2Master_Index5FFF)/sizeof(CCUCAN2Master_Index5FFF[0]), 0x5FFF},
};

const indextable * CCUCAN2Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1014: i = 2;break;
		case 0x1015: i = 3;break;
		case 0x1016: i = 4;break;
		case 0x1017: i = 5;*callbacks = CCUCAN2Master_Index1017_callbacks; break;
		case 0x1018: i = 6;break;
		case 0x1200: i = 7;break;
		case 0x1280: i = 8;break;
		case 0x1400: i = 9;break;
		case 0x1401: i = 10;break;
		case 0x1402: i = 11;break;
		case 0x1403: i = 12;break;
		case 0x1404: i = 13;break;
		case 0x1405: i = 14;break;
		case 0x1406: i = 15;break;
		case 0x1407: i = 16;break;
		case 0x1408: i = 17;break;
		case 0x1409: i = 18;break;
		case 0x1600: i = 19;break;
		case 0x1601: i = 20;break;
		case 0x1602: i = 21;break;
		case 0x1603: i = 22;break;
		case 0x1604: i = 23;break;
		case 0x1605: i = 24;break;
		case 0x1606: i = 25;break;
		case 0x1607: i = 26;break;
		case 0x1608: i = 27;break;
		case 0x1609: i = 28;break;
		case 0x1800: i = 29;*callbacks = CCUCAN2Master_Index1800_callbacks; break;
		case 0x1A00: i = 30;break;
		case 0x2008: i = 31;*callbacks = can2_HMITxDev_Time_callbacks; break;
		case 0x2057: i = 32;break;
		case 0x2058: i = 33;break;
		case 0x2059: i = 34;break;
		case 0x205A: i = 35;break;
		case 0x205B: i = 36;break;
		case 0x205C: i = 37;break;
		case 0x205D: i = 38;break;
		case 0x2076: i = 39;break;
		case 0x2077: i = 40;break;
		case 0x5FFE: i = 41;break;
		case 0x5FFF: i = 42;*callbacks = IAP_M_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &CCUCAN2Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status CCUCAN2Master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index CCUCAN2Master_firstIndex = {
  7, /* SDO_SVR */
  8, /* SDO_CLT */
  9, /* PDO_RCV */
  19, /* PDO_RCV_MAP */
  29, /* PDO_TRS */
  30 /* PDO_TRS_MAP */
};

const quick_index CCUCAN2Master_lastIndex = {
  7, /* SDO_SVR */
  8, /* SDO_CLT */
  18, /* PDO_RCV */
  28, /* PDO_RCV_MAP */
  29, /* PDO_TRS */
  30 /* PDO_TRS_MAP */
};

const UNS16 CCUCAN2Master_ObjdictSize = sizeof(CCUCAN2Master_objdict)/sizeof(CCUCAN2Master_objdict[0]); 

CO_Data CCUCAN2Master_Data = CANOPEN_NODE_DATA_INITIALIZER(CCUCAN2Master);

