
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MFDCAN2SLAVE_H
#define MFDCAN2SLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MFDCAN2Slave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MFDCAN2Slave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data MFDCAN2Slave_Data;
extern UNS8 can2_RxSyncDevc;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 can2_RxTime[6];		/* Mapped at index 0x2001, subindex 0x01 - 0x06 */
extern UNS8 can2_RxDoorSpeedTimBit[2];		/* Mapped at index 0x2002, subindex 0x01 - 0x02 */
extern UNS8 can2_RxAccTempTimBit[2];		/* Mapped at index 0x2003, subindex 0x01 - 0x02 */
extern UNS8 can2_RxBCUCmd[5];		/* Mapped at index 0x2004, subindex 0x01 - 0x05 */
extern UNS8 can2_RxVVVFCmd[6];		/* Mapped at index 0x2005, subindex 0x01 - 0x06 */
extern UNS8 can2_RxSIVCmd[3];		/* Mapped at index 0x2006, subindex 0x01 - 0x03 */
extern UNS8 can2_RxATCSdr1[6];		/* Mapped at index 0x2007, subindex 0x01 - 0x06 */
extern UNS8 can2_RxATCSdr2[5];		/* Mapped at index 0x2008, subindex 0x01 - 0x05 */
extern UNS8 can2_RxPISSdr1[8];		/* Mapped at index 0x2009, subindex 0x01 - 0x08 */
extern UNS8 can2_RxPISSdr2[8];		/* Mapped at index 0x200A, subindex 0x01 - 0x08 */
extern UNS8 can2_TxMFD1DI[2];		/* Mapped at index 0x200B, subindex 0x01 - 0x02 */
extern UNS8 can2_TxMFD2DI[2];		/* Mapped at index 0x200C, subindex 0x01 - 0x02 */
extern UNS8 can2_TxMFD3DI[2];		/* Mapped at index 0x200D, subindex 0x01 - 0x02 */
extern UNS8 can2_TxDoorSta1[8];		/* Mapped at index 0x200E, subindex 0x01 - 0x08 */
extern UNS8 can2_TxDoorSta2[8];		/* Mapped at index 0x200F, subindex 0x01 - 0x08 */
extern UNS8 can2_TxAccSta[8];		/* Mapped at index 0x2010, subindex 0x01 - 0x08 */
extern UNS8 can2_TxBCUSta1[8];		/* Mapped at index 0x2011, subindex 0x01 - 0x08 */
extern UNS8 can2_TxBCUSta2[8];		/* Mapped at index 0x2012, subindex 0x01 - 0x08 */
extern UNS8 can2_TxBCUSta3[8];		/* Mapped at index 0x2013, subindex 0x01 - 0x08 */
extern UNS8 can2_TxATCSta1[7];		/* Mapped at index 0x2014, subindex 0x01 - 0x07 */
extern UNS8 can2_TxATCSta2[8];		/* Mapped at index 0x2015, subindex 0x01 - 0x08 */
extern UNS8 can2_TxATCSta3[8];		/* Mapped at index 0x2016, subindex 0x01 - 0x08 */
extern UNS8 can2_TxATCSta4[4];		/* Mapped at index 0x2017, subindex 0x01 - 0x04 */
extern UNS8 can2_TxPISSta1[8];		/* Mapped at index 0x2018, subindex 0x01 - 0x08 */
extern UNS8 can2_TxPISSta2[3];		/* Mapped at index 0x2019, subindex 0x01 - 0x03 */
extern UNS8 can2_TxVVVF1Sta1[8];		/* Mapped at index 0x201A, subindex 0x01 - 0x08 */
extern UNS8 can2_TxVVVF1Sta2[6];		/* Mapped at index 0x201B, subindex 0x01 - 0x06 */
extern UNS8 can2_TxVVVF1Sta3[8];		/* Mapped at index 0x201C, subindex 0x01 - 0x08 */
extern UNS8 can2_TxVVVF1Sta4[8];		/* Mapped at index 0x201D, subindex 0x01 - 0x08 */
extern UNS8 can2_TxVVVF1Sta5[6];		/* Mapped at index 0x201E, subindex 0x01 - 0x06 */
extern UNS8 can2_TxVVVF2Sta1[8];		/* Mapped at index 0x201F, subindex 0x01 - 0x08 */
extern UNS8 can2_TxVVVF2Sta2[6];		/* Mapped at index 0x2020, subindex 0x01 - 0x06 */
extern UNS8 can2_TxVVVF2Sta3[8];		/* Mapped at index 0x2021, subindex 0x01 - 0x08 */
extern UNS8 can2_TxVVVF2Sta4[8];		/* Mapped at index 0x2022, subindex 0x01 - 0x08 */
extern UNS8 can2_TxVVVF2Sta5[6];		/* Mapped at index 0x2023, subindex 0x01 - 0x06 */
extern UNS8 can2_TxSIVSd1[7];		/* Mapped at index 0x2024, subindex 0x01 - 0x07 */
extern UNS8 can2_TxSIVSd2[8];		/* Mapped at index 0x2025, subindex 0x01 - 0x08 */
extern UNS8 can2_TxSIVSd3[3];		/* Mapped at index 0x2026, subindex 0x01 - 0x03 */
extern UNS8 can2_TxSubDevFault[2];		/* Mapped at index 0x2027, subindex 0x01 - 0x02 */
extern UNS8 can2_TxAccSta2[1];		/* Mapped at index 0x2028, subindex 0x01 - 0x01 */
extern UNS8 can2_TxATCTime[6];		/* Mapped at index 0x2029, subindex 0x01 - 0x06 */
extern UNS8 can2_TxMFD1SubFault[2];		/* Mapped at index 0x202A, subindex 0x01 - 0x02 */
extern UNS8 can2_TxMFD2SubFault[1];		/* Mapped at index 0x202B, subindex 0x01 - 0x01 */
extern UNS8 can2_TxMFD3SubFault[1];		/* Mapped at index 0x202C, subindex 0x01 - 0x01 */
extern UNS8 can2_TxACPSta1[8];		/* Mapped at index 0x202D, subindex 0x01 - 0x08 */
extern UNS8 can2_TxACPSta2[3];		/* Mapped at index 0x202E, subindex 0x01 - 0x03 */
extern UNS8 IAP_M_IAP_SEG[256];		/* Mapped at index 0x5FFF, subindex 0x01 */
extern UNS64 IAP_M_IAP_CMD;		/* Mapped at index 0x5FFF, subindex 0x02 */
extern UNS64 IAP_M_IAP_CMD_R;		/* Mapped at index 0x5FFF, subindex 0x03 */

#endif // MFDCAN2SLAVE_H
