#ifndef __MTD_CPU_CANADDRES_H__
#define __MTD_CPU_CANADDRES_H__


#include "stm32f4xx.h"
/*定义输入GPIO端口*/
#define  MTDCPU_CANADD0_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD0_GPIO 			 GPIOF
#define  MTDCPU_CANADD0_GPIO_PIN 	 GPIO_Pin_0
#define  MTDCPU_CANADD0_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD0_GPIO,MTDCPU_CANADD0_GPIO_PIN)

#define  MTDCPU_CANADD1_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD1_GPIO 			 GPIOF
#define  MTDCPU_CANADD1_GPIO_PIN 	 GPIO_Pin_1
#define  MTDCPU_CANADD1_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD1_GPIO,MTDCPU_CANADD1_GPIO_PIN)

#define  MTDCPU_CANADD2_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD2_GPIO 			 GPIOF
#define  MTDCPU_CANADD2_GPIO_PIN 	 GPIO_Pin_2
#define  MTDCPU_CANADD2_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD2_GPIO,MTDCPU_CANADD2_GPIO_PIN)

#define  MTDCPU_CANADD3_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD3_GPIO 			 GPIOF
#define  MTDCPU_CANADD3_GPIO_PIN 	 GPIO_Pin_3
#define  MTDCPU_CANADD3_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD3_GPIO,MTDCPU_CANADD3_GPIO_PIN)

#define  MTDCPU_CANADD4_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD4_GPIO 			 GPIOF
#define  MTDCPU_CANADD4_GPIO_PIN 	 GPIO_Pin_4
#define  MTDCPU_CANADD4_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD4_GPIO,MTDCPU_CANADD4_GPIO_PIN)

#define  MTDCPU_CANADD5_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD5_GPIO 			 GPIOF
#define  MTDCPU_CANADD5_GPIO_PIN 	 GPIO_Pin_5
#define  MTDCPU_CANADD5_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD5_GPIO,MTDCPU_CANADD5_GPIO_PIN)

#define  MTDCPU_CANADD6_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD6_GPIO 			 GPIOF
#define  MTDCPU_CANADD6_GPIO_PIN 	 GPIO_Pin_12
#define  MTDCPU_CANADD6_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD6_GPIO,MTDCPU_CANADD6_GPIO_PIN)

#define  MTDCPU_CANADD7_RCC      	 RCC_AHB1Periph_GPIOF
#define  MTDCPU_CANADD7_GPIO 			 GPIOF
#define  MTDCPU_CANADD7_GPIO_PIN 	 GPIO_Pin_13
#define  MTDCPU_CANADD7_READ()		 GPIO_ReadInputDataBit(MTDCPU_CANADD7_GPIO,MTDCPU_CANADD7_GPIO_PIN)

void MTDCPU_CanAdd_Gpio_Init(void);
uint8_t MTDCPU_CanAddVal(void);

#endif //__MTD_CPU_CANADDRES_H__
